import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1776860111130 implements MigrationInterface {
    name = 'Migrations1776860111130'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`websites\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by_id\` int UNSIGNED NULL, \`updated_by_id\` int UNSIGNED NULL, \`title\` varchar(255) NOT NULL, \`base_url\` varchar(255) NOT NULL, \`declaration_status\` int NOT NULL DEFAULT '0', \`declaration_updated_at\` timestamp NULL, \`stamp_status\` int NOT NULL DEFAULT '0', \`stamp_updated_at\` timestamp NULL, INDEX \`IDX_89acd61d6a2e8678b62b6cae90\` (\`created_by_id\`), INDEX \`IDX_fcf83138c2ef29f84a4b4298a8\` (\`updated_by_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`slug\` varchar(50) NOT NULL, \`display_name\` varchar(100) NOT NULL, \`description\` text NULL, UNIQUE INDEX \`IDX_881f72bac969d9a00a1a29e107\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`pages\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by_id\` int UNSIGNED NULL, \`updated_by_id\` int UNSIGNED NULL, \`url\` text NOT NULL, \`url_hash\` varchar(64) CHARACTER SET "ascii" COLLATE "ascii_general_ci" NOT NULL, \`inObservatory\` tinyint NOT NULL DEFAULT 0, \`type\` enum ('OFFICIAL', 'PRIVATE_STUDY') NOT NULL DEFAULT 'OFFICIAL', INDEX \`IDX_013b1eaf7f474ea4a78b827f44\` (\`created_by_id\`), INDEX \`IDX_45399fad693a2f3aec4280e6ab\` (\`updated_by_id\`), UNIQUE INDEX \`IDX_497707a1e3366254aba60ac1e5\` (\`url_hash\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`gov_users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`ccNumber\` varchar(255) NOT NULL, \`registerDate\` datetime NOT NULL, \`lastLogin\` datetime NOT NULL, UNIQUE INDEX \`IDX_b8ea176b6e67a6609faa768c5a\` (\`name\`), UNIQUE INDEX \`IDX_34eda2d5812bf2df384ecafe6b\` (\`ccNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`organizations\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by_id\` int UNSIGNED NULL, \`updated_by_id\` int UNSIGNED NULL, \`short_name\` varchar(100) NOT NULL, \`long_name\` varchar(255) NOT NULL, \`deletionMetadataDeleted_at\` datetime(6) NULL, \`deletionMetadataDeleted_by\` int UNSIGNED NULL, INDEX \`IDX_f56cb25675485f275a31825d67\` (\`created_by_id\`), INDEX \`IDX_f89edaa82db9896010870e7b19\` (\`updated_by_id\`), UNIQUE INDEX \`IDX_d0ea953dac7685a594fb8b4049\` (\`short_name\`), UNIQUE INDEX \`IDX_0c758a49ae46088a8d1b32ae3a\` (\`long_name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by_id\` int UNSIGNED NULL, \`updated_by_id\` int UNSIGNED NULL, \`username\` varchar(150) NOT NULL, \`password\` varchar(255) NOT NULL, \`full_name\` varchar(255) NULL, \`email\` varchar(255) NOT NULL, \`last_login\` timestamp NULL, \`unique_hash\` varchar(255) NOT NULL, \`role_id\` int UNSIGNED NOT NULL, \`gov_user_id\` int NULL, \`deletionMetadataDeleted_at\` datetime(6) NULL, \`deletionMetadataDeleted_by\` int UNSIGNED NULL, INDEX \`IDX_1bbd34899b8e74ef2a7f321280\` (\`created_by_id\`), INDEX \`IDX_80e310e761f458f272c20ea6ad\` (\`updated_by_id\`), UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` (\`username\`), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), UNIQUE INDEX \`REL_744bd1a9a91df9f50b4a35cfd5\` (\`gov_user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`directories\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by_id\` int UNSIGNED NULL, \`updated_by_id\` int UNSIGNED NULL, \`name\` varchar(255) NOT NULL, \`show_in_observatory\` tinyint(1) NOT NULL DEFAULT '0', \`method\` tinyint(1) NOT NULL DEFAULT '0', INDEX \`IDX_8c98224c364fef92e53c991b19\` (\`created_by_id\`), INDEX \`IDX_973da17dea8c1b80389a5a366b\` (\`updated_by_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tags\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by_id\` int UNSIGNED NULL, \`updated_by_id\` int UNSIGNED NULL, \`name\` varchar(255) NOT NULL, INDEX \`IDX_f6e2dfaca4aed5f8381e4e7b20\` (\`created_by_id\`), INDEX \`IDX_e28a966f446a4e3b9cfcb7c4c9\` (\`updated_by_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`observatory\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`global_statistics\` mediumtext NOT NULL, \`type\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`observatory_sync_status\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`status\` enum ('idle', 'running', 'completed', 'failed', 'interrupted') NOT NULL DEFAULT 'idle', \`type\` enum ('auto', 'manual') NOT NULL DEFAULT 'auto', \`startTime\` datetime NULL, \`endTime\` datetime NULL, \`totalChunks\` int NOT NULL DEFAULT '0', \`processedChunks\` int NOT NULL DEFAULT '0', \`totalDirectories\` int NOT NULL DEFAULT '0', \`processedDirectories\` int NOT NULL DEFAULT '0', \`errorMessage\` text NULL, \`processId\` varchar(50) NULL, \`namespace\` varchar(50) NULL, \`amsid\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`functional_aspects\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`websiteId\` int NOT NULL, \`date\` datetime NOT NULL, \`conformance\` double NOT NULL, \`result\` text NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`content_aspects\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`websiteId\` int NOT NULL, \`date\` datetime NOT NULL, \`conformance\` double NOT NULL, \`result\` text NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`accessibility_statements\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by_id\` int UNSIGNED NULL, \`updated_by_id\` int UNSIGNED NULL, \`url\` varchar(255) NOT NULL, \`conformance\` varchar(255) NOT NULL, \`evidence\` text NOT NULL, \`seal\` varchar(255) NOT NULL, \`statement_date\` datetime NULL, \`state\` enum ('completeStatement', 'incompleteStatement', 'possibleStatement') NOT NULL, \`hash\` varchar(255) NOT NULL, \`website_id\` int UNSIGNED NOT NULL, INDEX \`IDX_5eab8023e9d8cfe18f1dcf4dfd\` (\`created_by_id\`), INDEX \`IDX_584b3e846ce4fffa177863d2fc\` (\`updated_by_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`automatic_evaluations\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`title\` varchar(255) NULL, \`url\` varchar(255) NULL, \`sample\` varchar(255) NULL, \`tool\` varchar(255) NULL, \`summary\` text NULL, \`date\` datetime NULL, \`Accessibility_Statement_Id\` int UNSIGNED NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`manual_evaluations\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`title\` varchar(255) NULL, \`url\` varchar(255) NULL, \`sample\` varchar(255) NULL, \`heuristicsPassed\` int NULL, \`heuristicsTotal\` int NULL, \`summary\` text NULL, \`date\` datetime NULL, \`Accessibility_Statement_Id\` int UNSIGNED NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_evaluations\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`title\` varchar(255) NULL, \`url\` varchar(255) NULL, \`participants\` varchar(255) NULL, \`process\` varchar(255) NULL, \`summary\` text NULL, \`date\` datetime NULL, \`Accessibility_Statement_Id\` int UNSIGNED NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contacts\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`contactType\` varchar(255) NOT NULL, \`contact\` varchar(255) NOT NULL, \`Accessibility_Statement_Id\` int UNSIGNED NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`collection_dates\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`invalid_tokens\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`token\` varchar(1024) CHARACTER SET "ascii" COLLATE "ascii_general_ci" NOT NULL, \`expires_at\` timestamp NOT NULL, INDEX \`IDX_INVALID_TOKEN_HASH\` (\`token\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`crawl_websites\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by_id\` int UNSIGNED NULL, \`updated_by_id\` int UNSIGNED NULL, \`base_url\` varchar(255) NOT NULL, \`website_id\` int UNSIGNED NOT NULL, \`max_depth\` int NOT NULL DEFAULT '0', \`is_done\` tinyint NOT NULL DEFAULT 0, \`tag_id\` int NULL, INDEX \`IDX_117d18a1cdc7ea43fdb2de227a\` (\`created_by_id\`), INDEX \`IDX_b93a0744a1c6018f494c798e52\` (\`updated_by_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`crawl_pages\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`crawl_website_id\` int UNSIGNED NOT NULL, \`url\` text NOT NULL, \`url_hash\` varchar(64) CHARACTER SET "ascii" COLLATE "ascii_general_ci" NOT NULL, UNIQUE INDEX \`IDX_46d4bc0bca67b8be2db616e531\` (\`url_hash\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`evaluations\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by_id\` int UNSIGNED NULL, \`updated_by_id\` int UNSIGNED NULL, \`pageId\` int NOT NULL, \`pageTitle\` varchar(255) NULL, \`score\` decimal(4,1) NOT NULL, \`A\` int NOT NULL, \`AA\` int NOT NULL, \`AAA\` int NOT NULL, \`context\` enum ('AMS', 'MONITOR', 'STUDY') NOT NULL, \`elementCount\` text NOT NULL, \`tagCount\` text NOT NULL, INDEX \`IDX_960d0e425a62e403f0f2cd0d4c\` (\`created_by_id\`), INDEX \`IDX_2286bca9188c3f484d6cd14ea8\` (\`updated_by_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`transaction_aspects\` (\`id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`websiteId\` int NOT NULL, \`date\` datetime NOT NULL, \`conformance\` double NOT NULL, \`result\` text NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`website_tags\` (\`website_id\` int UNSIGNED NOT NULL, \`tag_id\` int UNSIGNED NOT NULL, INDEX \`IDX_6b18c94a583c7d5b39963c7987\` (\`website_id\`), INDEX \`IDX_19cc89130b624d160e5e89ea3f\` (\`tag_id\`), PRIMARY KEY (\`website_id\`, \`tag_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`website_organizations\` (\`website_id\` int UNSIGNED NOT NULL, \`organization_id\` int UNSIGNED NOT NULL, INDEX \`IDX_07404f5418c9656f7e7f372a5b\` (\`website_id\`), INDEX \`IDX_ca225279c1fe1482d488af85e3\` (\`organization_id\`), PRIMARY KEY (\`website_id\`, \`organization_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`website_pages\` (\`website_id\` int UNSIGNED NOT NULL, \`page_id\` int UNSIGNED NOT NULL, INDEX \`IDX_f904a75e615407d0c90ed939cf\` (\`website_id\`), INDEX \`IDX_401c4ba425f4807c1e7485298f\` (\`page_id\`), PRIMARY KEY (\`website_id\`, \`page_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`page_visibility_roles\` (\`page_id\` int UNSIGNED NOT NULL, \`role_id\` int UNSIGNED NOT NULL, INDEX \`IDX_06510e00882813caccbdb2aad4\` (\`page_id\`), INDEX \`IDX_eeb93f9c76e3b06d5c8d7deb5c\` (\`role_id\`), PRIMARY KEY (\`page_id\`, \`role_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`directory_tags\` (\`directory_id\` int UNSIGNED NOT NULL, \`tag_id\` int UNSIGNED NOT NULL, INDEX \`IDX_74365a2854892881bd55457b97\` (\`directory_id\`), INDEX \`IDX_7bf65fbbb7fb3710c830db0ac8\` (\`tag_id\`), PRIMARY KEY (\`directory_id\`, \`tag_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tag_directories\` (\`tagsId\` int UNSIGNED NOT NULL, \`directoriesId\` int UNSIGNED NOT NULL, INDEX \`IDX_78dff70ad38b9f72a40e77a201\` (\`tagsId\`), INDEX \`IDX_a0bdf34131e398a3b534409b7c\` (\`directoriesId\`), PRIMARY KEY (\`tagsId\`, \`directoriesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`websites\` ADD CONSTRAINT \`FK_89acd61d6a2e8678b62b6cae900\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`websites\` ADD CONSTRAINT \`FK_fcf83138c2ef29f84a4b4298a8b\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD CONSTRAINT \`FK_013b1eaf7f474ea4a78b827f445\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pages\` ADD CONSTRAINT \`FK_45399fad693a2f3aec4280e6aba\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organizations\` ADD CONSTRAINT \`FK_f56cb25675485f275a31825d67d\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organizations\` ADD CONSTRAINT \`FK_f89edaa82db9896010870e7b196\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organizations\` ADD CONSTRAINT \`FK_2ca9e0d32e2764eb77b6045060c\` FOREIGN KEY (\`deletionMetadataDeleted_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_1bbd34899b8e74ef2a7f3212806\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_80e310e761f458f272c20ea6add\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_a2cecd1a3531c0b041e29ba46e1\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_744bd1a9a91df9f50b4a35cfd55\` FOREIGN KEY (\`gov_user_id\`) REFERENCES \`gov_users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_94843906435d0af42d293525bbd\` FOREIGN KEY (\`deletionMetadataDeleted_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`directories\` ADD CONSTRAINT \`FK_8c98224c364fef92e53c991b19d\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`directories\` ADD CONSTRAINT \`FK_973da17dea8c1b80389a5a366b6\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tags\` ADD CONSTRAINT \`FK_f6e2dfaca4aed5f8381e4e7b208\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tags\` ADD CONSTRAINT \`FK_e28a966f446a4e3b9cfcb7c4c9b\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`accessibility_statements\` ADD CONSTRAINT \`FK_5eab8023e9d8cfe18f1dcf4dfd9\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`accessibility_statements\` ADD CONSTRAINT \`FK_584b3e846ce4fffa177863d2fc7\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`accessibility_statements\` ADD CONSTRAINT \`FK_46594336ac71bfde637ed7c9094\` FOREIGN KEY (\`website_id\`) REFERENCES \`websites\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`automatic_evaluations\` ADD CONSTRAINT \`FK_a2d6bcf199cb803c7a9f709ebd6\` FOREIGN KEY (\`Accessibility_Statement_Id\`) REFERENCES \`accessibility_statements\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`manual_evaluations\` ADD CONSTRAINT \`FK_802c5504ec2d0024ba436eb4240\` FOREIGN KEY (\`Accessibility_Statement_Id\`) REFERENCES \`accessibility_statements\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_evaluations\` ADD CONSTRAINT \`FK_d7ee4cf61386ee606ba28f2f6d4\` FOREIGN KEY (\`Accessibility_Statement_Id\`) REFERENCES \`accessibility_statements\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contacts\` ADD CONSTRAINT \`FK_c71b556c48db6df540c469b3a33\` FOREIGN KEY (\`Accessibility_Statement_Id\`) REFERENCES \`accessibility_statements\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`crawl_websites\` ADD CONSTRAINT \`FK_117d18a1cdc7ea43fdb2de227a4\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`crawl_websites\` ADD CONSTRAINT \`FK_b93a0744a1c6018f494c798e522\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`crawl_websites\` ADD CONSTRAINT \`FK_e929e966db6a1cfab54fa4aa799\` FOREIGN KEY (\`website_id\`) REFERENCES \`websites\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`crawl_pages\` ADD CONSTRAINT \`FK_0d02e433e129f7295f36a46d7c9\` FOREIGN KEY (\`crawl_website_id\`) REFERENCES \`crawl_websites\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evaluations\` ADD CONSTRAINT \`FK_960d0e425a62e403f0f2cd0d4ca\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`evaluations\` ADD CONSTRAINT \`FK_2286bca9188c3f484d6cd14ea84\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`website_tags\` ADD CONSTRAINT \`FK_6b18c94a583c7d5b39963c7987d\` FOREIGN KEY (\`website_id\`) REFERENCES \`websites\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`website_tags\` ADD CONSTRAINT \`FK_19cc89130b624d160e5e89ea3f4\` FOREIGN KEY (\`tag_id\`) REFERENCES \`tags\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`website_organizations\` ADD CONSTRAINT \`FK_07404f5418c9656f7e7f372a5bc\` FOREIGN KEY (\`website_id\`) REFERENCES \`websites\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`website_organizations\` ADD CONSTRAINT \`FK_ca225279c1fe1482d488af85e30\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organizations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`website_pages\` ADD CONSTRAINT \`FK_f904a75e615407d0c90ed939cf5\` FOREIGN KEY (\`website_id\`) REFERENCES \`websites\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`website_pages\` ADD CONSTRAINT \`FK_401c4ba425f4807c1e7485298f8\` FOREIGN KEY (\`page_id\`) REFERENCES \`pages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`page_visibility_roles\` ADD CONSTRAINT \`FK_06510e00882813caccbdb2aad42\` FOREIGN KEY (\`page_id\`) REFERENCES \`pages\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`page_visibility_roles\` ADD CONSTRAINT \`FK_eeb93f9c76e3b06d5c8d7deb5c9\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`directory_tags\` ADD CONSTRAINT \`FK_74365a2854892881bd55457b976\` FOREIGN KEY (\`directory_id\`) REFERENCES \`directories\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`directory_tags\` ADD CONSTRAINT \`FK_7bf65fbbb7fb3710c830db0ac80\` FOREIGN KEY (\`tag_id\`) REFERENCES \`tags\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tag_directories\` ADD CONSTRAINT \`FK_78dff70ad38b9f72a40e77a201d\` FOREIGN KEY (\`tagsId\`) REFERENCES \`tags\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`tag_directories\` ADD CONSTRAINT \`FK_a0bdf34131e398a3b534409b7c9\` FOREIGN KEY (\`directoriesId\`) REFERENCES \`directories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`tag_directories\` DROP FOREIGN KEY \`FK_a0bdf34131e398a3b534409b7c9\``);
        await queryRunner.query(`ALTER TABLE \`tag_directories\` DROP FOREIGN KEY \`FK_78dff70ad38b9f72a40e77a201d\``);
        await queryRunner.query(`ALTER TABLE \`directory_tags\` DROP FOREIGN KEY \`FK_7bf65fbbb7fb3710c830db0ac80\``);
        await queryRunner.query(`ALTER TABLE \`directory_tags\` DROP FOREIGN KEY \`FK_74365a2854892881bd55457b976\``);
        await queryRunner.query(`ALTER TABLE \`page_visibility_roles\` DROP FOREIGN KEY \`FK_eeb93f9c76e3b06d5c8d7deb5c9\``);
        await queryRunner.query(`ALTER TABLE \`page_visibility_roles\` DROP FOREIGN KEY \`FK_06510e00882813caccbdb2aad42\``);
        await queryRunner.query(`ALTER TABLE \`website_pages\` DROP FOREIGN KEY \`FK_401c4ba425f4807c1e7485298f8\``);
        await queryRunner.query(`ALTER TABLE \`website_pages\` DROP FOREIGN KEY \`FK_f904a75e615407d0c90ed939cf5\``);
        await queryRunner.query(`ALTER TABLE \`website_organizations\` DROP FOREIGN KEY \`FK_ca225279c1fe1482d488af85e30\``);
        await queryRunner.query(`ALTER TABLE \`website_organizations\` DROP FOREIGN KEY \`FK_07404f5418c9656f7e7f372a5bc\``);
        await queryRunner.query(`ALTER TABLE \`website_tags\` DROP FOREIGN KEY \`FK_19cc89130b624d160e5e89ea3f4\``);
        await queryRunner.query(`ALTER TABLE \`website_tags\` DROP FOREIGN KEY \`FK_6b18c94a583c7d5b39963c7987d\``);
        await queryRunner.query(`ALTER TABLE \`evaluations\` DROP FOREIGN KEY \`FK_2286bca9188c3f484d6cd14ea84\``);
        await queryRunner.query(`ALTER TABLE \`evaluations\` DROP FOREIGN KEY \`FK_960d0e425a62e403f0f2cd0d4ca\``);
        await queryRunner.query(`ALTER TABLE \`crawl_pages\` DROP FOREIGN KEY \`FK_0d02e433e129f7295f36a46d7c9\``);
        await queryRunner.query(`ALTER TABLE \`crawl_websites\` DROP FOREIGN KEY \`FK_e929e966db6a1cfab54fa4aa799\``);
        await queryRunner.query(`ALTER TABLE \`crawl_websites\` DROP FOREIGN KEY \`FK_b93a0744a1c6018f494c798e522\``);
        await queryRunner.query(`ALTER TABLE \`crawl_websites\` DROP FOREIGN KEY \`FK_117d18a1cdc7ea43fdb2de227a4\``);
        await queryRunner.query(`ALTER TABLE \`contacts\` DROP FOREIGN KEY \`FK_c71b556c48db6df540c469b3a33\``);
        await queryRunner.query(`ALTER TABLE \`user_evaluations\` DROP FOREIGN KEY \`FK_d7ee4cf61386ee606ba28f2f6d4\``);
        await queryRunner.query(`ALTER TABLE \`manual_evaluations\` DROP FOREIGN KEY \`FK_802c5504ec2d0024ba436eb4240\``);
        await queryRunner.query(`ALTER TABLE \`automatic_evaluations\` DROP FOREIGN KEY \`FK_a2d6bcf199cb803c7a9f709ebd6\``);
        await queryRunner.query(`ALTER TABLE \`accessibility_statements\` DROP FOREIGN KEY \`FK_46594336ac71bfde637ed7c9094\``);
        await queryRunner.query(`ALTER TABLE \`accessibility_statements\` DROP FOREIGN KEY \`FK_584b3e846ce4fffa177863d2fc7\``);
        await queryRunner.query(`ALTER TABLE \`accessibility_statements\` DROP FOREIGN KEY \`FK_5eab8023e9d8cfe18f1dcf4dfd9\``);
        await queryRunner.query(`ALTER TABLE \`tags\` DROP FOREIGN KEY \`FK_e28a966f446a4e3b9cfcb7c4c9b\``);
        await queryRunner.query(`ALTER TABLE \`tags\` DROP FOREIGN KEY \`FK_f6e2dfaca4aed5f8381e4e7b208\``);
        await queryRunner.query(`ALTER TABLE \`directories\` DROP FOREIGN KEY \`FK_973da17dea8c1b80389a5a366b6\``);
        await queryRunner.query(`ALTER TABLE \`directories\` DROP FOREIGN KEY \`FK_8c98224c364fef92e53c991b19d\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_94843906435d0af42d293525bbd\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_744bd1a9a91df9f50b4a35cfd55\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_a2cecd1a3531c0b041e29ba46e1\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_80e310e761f458f272c20ea6add\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_1bbd34899b8e74ef2a7f3212806\``);
        await queryRunner.query(`ALTER TABLE \`organizations\` DROP FOREIGN KEY \`FK_2ca9e0d32e2764eb77b6045060c\``);
        await queryRunner.query(`ALTER TABLE \`organizations\` DROP FOREIGN KEY \`FK_f89edaa82db9896010870e7b196\``);
        await queryRunner.query(`ALTER TABLE \`organizations\` DROP FOREIGN KEY \`FK_f56cb25675485f275a31825d67d\``);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP FOREIGN KEY \`FK_45399fad693a2f3aec4280e6aba\``);
        await queryRunner.query(`ALTER TABLE \`pages\` DROP FOREIGN KEY \`FK_013b1eaf7f474ea4a78b827f445\``);
        await queryRunner.query(`ALTER TABLE \`websites\` DROP FOREIGN KEY \`FK_fcf83138c2ef29f84a4b4298a8b\``);
        await queryRunner.query(`ALTER TABLE \`websites\` DROP FOREIGN KEY \`FK_89acd61d6a2e8678b62b6cae900\``);
        await queryRunner.query(`DROP INDEX \`IDX_a0bdf34131e398a3b534409b7c\` ON \`tag_directories\``);
        await queryRunner.query(`DROP INDEX \`IDX_78dff70ad38b9f72a40e77a201\` ON \`tag_directories\``);
        await queryRunner.query(`DROP TABLE \`tag_directories\``);
        await queryRunner.query(`DROP INDEX \`IDX_7bf65fbbb7fb3710c830db0ac8\` ON \`directory_tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_74365a2854892881bd55457b97\` ON \`directory_tags\``);
        await queryRunner.query(`DROP TABLE \`directory_tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_eeb93f9c76e3b06d5c8d7deb5c\` ON \`page_visibility_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_06510e00882813caccbdb2aad4\` ON \`page_visibility_roles\``);
        await queryRunner.query(`DROP TABLE \`page_visibility_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_401c4ba425f4807c1e7485298f\` ON \`website_pages\``);
        await queryRunner.query(`DROP INDEX \`IDX_f904a75e615407d0c90ed939cf\` ON \`website_pages\``);
        await queryRunner.query(`DROP TABLE \`website_pages\``);
        await queryRunner.query(`DROP INDEX \`IDX_ca225279c1fe1482d488af85e3\` ON \`website_organizations\``);
        await queryRunner.query(`DROP INDEX \`IDX_07404f5418c9656f7e7f372a5b\` ON \`website_organizations\``);
        await queryRunner.query(`DROP TABLE \`website_organizations\``);
        await queryRunner.query(`DROP INDEX \`IDX_19cc89130b624d160e5e89ea3f\` ON \`website_tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_6b18c94a583c7d5b39963c7987\` ON \`website_tags\``);
        await queryRunner.query(`DROP TABLE \`website_tags\``);
        await queryRunner.query(`DROP TABLE \`transaction_aspects\``);
        await queryRunner.query(`DROP INDEX \`IDX_2286bca9188c3f484d6cd14ea8\` ON \`evaluations\``);
        await queryRunner.query(`DROP INDEX \`IDX_960d0e425a62e403f0f2cd0d4c\` ON \`evaluations\``);
        await queryRunner.query(`DROP TABLE \`evaluations\``);
        await queryRunner.query(`DROP INDEX \`IDX_46d4bc0bca67b8be2db616e531\` ON \`crawl_pages\``);
        await queryRunner.query(`DROP TABLE \`crawl_pages\``);
        await queryRunner.query(`DROP INDEX \`IDX_b93a0744a1c6018f494c798e52\` ON \`crawl_websites\``);
        await queryRunner.query(`DROP INDEX \`IDX_117d18a1cdc7ea43fdb2de227a\` ON \`crawl_websites\``);
        await queryRunner.query(`DROP TABLE \`crawl_websites\``);
        await queryRunner.query(`DROP INDEX \`IDX_INVALID_TOKEN_HASH\` ON \`invalid_tokens\``);
        await queryRunner.query(`DROP TABLE \`invalid_tokens\``);
        await queryRunner.query(`DROP TABLE \`collection_dates\``);
        await queryRunner.query(`DROP TABLE \`contacts\``);
        await queryRunner.query(`DROP TABLE \`user_evaluations\``);
        await queryRunner.query(`DROP TABLE \`manual_evaluations\``);
        await queryRunner.query(`DROP TABLE \`automatic_evaluations\``);
        await queryRunner.query(`DROP INDEX \`IDX_584b3e846ce4fffa177863d2fc\` ON \`accessibility_statements\``);
        await queryRunner.query(`DROP INDEX \`IDX_5eab8023e9d8cfe18f1dcf4dfd\` ON \`accessibility_statements\``);
        await queryRunner.query(`DROP TABLE \`accessibility_statements\``);
        await queryRunner.query(`DROP TABLE \`content_aspects\``);
        await queryRunner.query(`DROP TABLE \`functional_aspects\``);
        await queryRunner.query(`DROP TABLE \`observatory_sync_status\``);
        await queryRunner.query(`DROP TABLE \`observatory\``);
        await queryRunner.query(`DROP INDEX \`IDX_e28a966f446a4e3b9cfcb7c4c9\` ON \`tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_f6e2dfaca4aed5f8381e4e7b20\` ON \`tags\``);
        await queryRunner.query(`DROP TABLE \`tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_973da17dea8c1b80389a5a366b\` ON \`directories\``);
        await queryRunner.query(`DROP INDEX \`IDX_8c98224c364fef92e53c991b19\` ON \`directories\``);
        await queryRunner.query(`DROP TABLE \`directories\``);
        await queryRunner.query(`DROP INDEX \`REL_744bd1a9a91df9f50b4a35cfd5\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_80e310e761f458f272c20ea6ad\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_1bbd34899b8e74ef2a7f321280\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_0c758a49ae46088a8d1b32ae3a\` ON \`organizations\``);
        await queryRunner.query(`DROP INDEX \`IDX_d0ea953dac7685a594fb8b4049\` ON \`organizations\``);
        await queryRunner.query(`DROP INDEX \`IDX_f89edaa82db9896010870e7b19\` ON \`organizations\``);
        await queryRunner.query(`DROP INDEX \`IDX_f56cb25675485f275a31825d67\` ON \`organizations\``);
        await queryRunner.query(`DROP TABLE \`organizations\``);
        await queryRunner.query(`DROP INDEX \`IDX_34eda2d5812bf2df384ecafe6b\` ON \`gov_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_b8ea176b6e67a6609faa768c5a\` ON \`gov_users\``);
        await queryRunner.query(`DROP TABLE \`gov_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_497707a1e3366254aba60ac1e5\` ON \`pages\``);
        await queryRunner.query(`DROP INDEX \`IDX_45399fad693a2f3aec4280e6ab\` ON \`pages\``);
        await queryRunner.query(`DROP INDEX \`IDX_013b1eaf7f474ea4a78b827f44\` ON \`pages\``);
        await queryRunner.query(`DROP TABLE \`pages\``);
        await queryRunner.query(`DROP INDEX \`IDX_881f72bac969d9a00a1a29e107\` ON \`roles\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_fcf83138c2ef29f84a4b4298a8\` ON \`websites\``);
        await queryRunner.query(`DROP INDEX \`IDX_89acd61d6a2e8678b62b6cae90\` ON \`websites\``);
        await queryRunner.query(`DROP TABLE \`websites\``);
    }

}
