DROP TABLE IF EXISTS rules_source;
CREATE TABLE IF NOT EXISTS rules_source (
    rule_id String,
    rule_title String,
    rule_description String,
    rule_type String,
    target_element String,
    test_method String,
    weight_score UInt8,
    wcag_level String,
    trust_factor Float32,
    wcag_success_criteria Array(String),
    expected_result String
) ENGINE = MergeTree() 
ORDER BY rule_id;

DROP DICTIONARY IF EXISTS rules_dict;
CREATE DICTIONARY IF NOT EXISTS rules_dict (
    rule_id String,
    rule_title String,
    rule_description String,
    rule_type String,
    target_element String,
    test_method String,
    weight_score UInt8,
    wcag_level String,
    trust_factor Float32,
    wcag_success_criteria Array(String),
    expected_result String
)
PRIMARY KEY rule_id
SOURCE(CLICKHOUSE(
    TABLE 'rules_source' 
    DB 'accessibility'
    USER 'default'
    PASSWORD 'your_clickhouse_password' 
))
LIFETIME(MIN 0 MAX 3600)
LAYOUT(HASHED());



INSERT INTO accessibility.rules_source (rule_id, rule_title, rule_description, rule_type, target_element, test_method, weight_score, wcag_level, trust_factor, wcag_success_criteria, expected_result) VALUES 
('a_01a', 'Encontrei páginas em que o primeiro link permite saltar para o conteúdo principal', '<p>Disponibilize no topo da página um link que permita saltar diretamente para o conteúdo principal da mesma. Este link facilita a navegação a muitos utilizadores, nomeadamente os que usam software de seleção por varrimento. Estes utilizadores usam a visão para ler a informação pelo que o link tem de estar sempre visível ou ficar visível ao receber o foco.</p>', 'true', 'a', 'aSkipFirst', 10, 'A', 0.7, ['2.4.1'], 'warning'),
('a_01b', 'Encontrei páginas em que o primeiro link não permite saltar para o conteúdo principal da página', '<p>Disponibilize no topo da página um link que permita saltar diretamente para o conteúdo principal da mesma. Este link facilita a navegação a muitos utilizadores, nomeadamente os que usam software de seleção por varrimento. Estes utilizadores usam a visão para ler a informação pelo que o link tem de estar sempre visível ou ficar visível ao receber o foco.</p>', 'fals', 'a', 'aSkipFirstNo', 3, 'A', 0.9, ['2.4.1'], 'failed'),
('a_02a', 'Encontrei páginas em que não existem links para saltar blocos de texto', '<p>Verifique se de facto os links que encontrei proporcionam os saltos de conteúdo mais adequados; se os mesmos estão sempre visíveis ou se ficam visíveis ao receberem o foco via teclado.</p>', 'fals', 'a', 'aSkipNo', 3, 'A', 0.9, ['2.4.1'], 'failed'),
('a_02b', 'Encontrei páginas em que existem links para saltar blocos de texto', '<p>Verifique se de facto os links que encontrei proporcionam os saltos de conteúdo mais adequados; se os mesmos estão sempre visíveis ou se ficam visíveis ao receberem o foco via teclado.</p>', 'true', 'a', 'aSkip', 10, 'A', 0.7, ['2.4.1'], 'warning'),
('a_03', 'Encontrei <mark>{{value}}</mark> link cujo conteúdo está vazio. Ou melhor, é composto apenas por uma imagem e a imagem tem por equivalente textual alternativo um caráter vazio (i.e. <code>alt=\\"\\"</code>).', '<p>Esta falha ocorre sempre que um link é composto por uma imagem e a imagem tem um equivalente textual alternativo vazio - desconfio que os utilizadores de Tecnologias de Apoio não saibam qual é o seu destino ou para que serve, ou que possam mesmo nem sequer dar conta que o link existe.</p>', 'decr', 'a', 'aImgAltNo', 3, 'A', 1, ['2.4.4', '2.4.9', '4.1.2'], 'failed'),
('a_04', 'Não encontrei links', '<p>A natureza da WWW é disponibilizar nas páginas links para outras páginas relacionadas. É isso que permite aos utilizadores navegar pela informação. Uma página Web sem links é, à priori, estranho!</p>', 'fals', 'all', 'a', 3, 'AA', 1, ['2.4.5'], 'failed'),
('a_05', 'Encontrei páginas em que o atributo title do link se limita a repetir o texto do link', '<p>O atributo title é utilizado para proporcionar informação complementar à existente no texto do link. O atributo title e o texto do link devem ser suficientes para compreender o propósito do link.</p>', 'prop', 'a', 'aTitleMatch', 5, 'A', 1, ['2.4.4', '2.4.9'], 'failed'),
('a_06', 'Encontrei páginas com links adjacentes que apontam para o mesmo destino', '<p>No caso de links adjacentes que apontam exatamente para o mesmo recurso é sinal que os podemos agregar num só link. Geralmente, nestes casos, temos a sensação visual de estar perante um único link mas no caso de alguns utilizadores de Tecnologias de Apoio surgem duplicados, podendo resultar confuso.</p>', 'decr', 'a', 'aAdjacentSame', 5, 'A', 1, ['1.1.1', '2.4.4', '2.4.9'], 'failed'),
('a_07', 'Encontrei links adjacentes que não estão dentro de um elemento <code>nav</code>', '<p>O elemento <code>&lt;nav&gt;</code> é usado para agrupar links de navegação relacionados. Verifique se os links que identifiquei como relacionados estão agrupados dentro de um elemento <code>&lt;nav&gt;</code>.</p>', 'fals', 'a', 'aGroupNo', 5, 'A', 1, ['2.4.1'], 'failed'),
('a_09', 'Encontrei páginas com links com o mesmo texto mas que apontam para destinos diferentes', '<p>É importante que os utilizadores consigam determinar o propósito e o destino do link sem recorrer ao contexto em que ele se encontra. Há utilizadores cujas Tecnologias de Apoio lhes fornecem todos os links da página em forma de listagem, sem qualquer contexto.</p>', 'decr', 'a', 'aSameText', 3, 'AAA', 1, ['2.4.9'], 'warning'),
('a_10', 'Encontrei páginas com links com nome acessível não vazio', '<p>A descrição de um link permite ao utilizador compreender o destino da ligação e decidir se quer seguir a ligação ou não.</p>', 'true', 'all', 'linkAName', 10, 'A', 1, ['4.1.2'], 'passed'),
('a_11', 'Encontrei páginas com links sem nome acessível', '<p>A descrição de um link permite ao utilizador compreender o destino da ligação e decidir se quer seguir a ligação ou não.</p>', 'prop', 'a', 'linkNotAName', 3, 'A', 1, ['4.1.2'], 'failed'),
('a_12', 'Encontrei páginas com Links com o mesmo nome acessível e contexto com o mesmo destino', '<p>É importante que links com o mesmo nome acessível e que partilhem o mesmo contexto não levem para destinos com diferentes propósitos, pois isso confundirá o utilizador.</p>', 'true', 'all', 'linkIdentAName', 10, 'A', 1, ['2.4.4'], 'passed'),
('a_13', 'Encontrei páginas com Links com o mesmo nome acessível e contexto mas destinos diferentes', '<p>É importante que links com o mesmo nome acessível e que partilhem o mesmo contexto não levem para destinos com diferentes propósitos, pois isso confundirá o utilizador.</p>', 'prop', 'a', 'linkIdentANameNot', 3, 'A', 1, ['2.4.4'], 'warning'),
('abbr_01', 'Encontrei páginas onde há abreviaturas que não têm a correspondente extensão', '<p>Marque as abreviaturas e/ou acrónimos com a respetiva extensão. No caso de HTML5 usa-se o elemento <code>&lt;abbr&gt;</code> quer para marcar abreviaturas quer para marcar acrónimos. Por exemplo: <code>&lt;abbr title="Fundação para a Ciência e a Tecnologia"&gt;</code>FCT<code>&lt;/abbr&gt;</code></p>', 'true', 'all', 'abbrNo', 5, 'AAA', 1, ['3.1.4'], 'failed'),
('area_01a', 'Encontrei páginas em que todos os elementos <area> ativos encontrados usam o atributo alt', '<p>Verifique se o equivalente textual alternativo existente nas áreas ativas dos mapas de imagem serve informação ou função igual à desempenhada pelo mapa de imagem na página.</p>', 'fals', 'area', 'areaAltYes', 10, 'A', 0.5, ['1.1.1', '2.4.4', '2.4.9'], 'passed'),
('area_01b', 'Encontrei páginas em que os elementos <area> não têm o atributo alt ou então o atributo alt está vazio', '<p>Verifique se o equivalente textual alternativo existente nos botões gráficos serve informação ou função igual à desempenhada pelo botão gráfico na página.</p>', 'prop', 'area', 'areaAltNo', 1, 'A', 1, ['1.1.1'], 'failed'),
('aria_01', 'Encontrei elementos dentro do seu contexto obrigatório', '<p>Quando se define explicitamente o papel semântico de um elemento, deve garantir-se que se ele tiver um contexto obrigatório, os pais do elemento fornecem esse contexto.</p>', 'true', 'all', 'ariaCntxRole', 10, 'A', 1, ['1.3.1'], 'passed'),
('aria_02', 'Encontrei elementos com filhos obrigatórios', '<p>Quando se define explicitamente o papel semântico de um elemento, deve garantir-se que se ele tiver filhos obrigatórios, pelo menos um destes existe.</p>', 'true', 'all', 'ariaReqElem', 10, 'A', 1, ['1.3.1'], 'passed'),
('aria_03', 'Encontrei estados e propriedades ARIA de tipo válido', '<p>A especificação ARIA define o tipo de valores que os estados e as propriedades ARIA podem assumir. Garanta que usa valores do tipo correto, caso contrário o seu código não irá produzir o efeito desejado.</p>', 'true', 'all', 'ariaStValid', 10, 'A', 1, ['1.3.1', '4.1.2'], 'passed'),
('aria_04', 'Encontrei estados e propriedades ARIA de tipo inválido', '<p>A especificação ARIA define o tipo de valores que os estados e as propriedades ARIA podem assumir. Garanta que usa valores do tipo correto, caso contrário o seu código não irá produzir o efeito desejado.</p>', 'fals', 'all', 'ariaStNotValid', 1, 'A', 1, ['1.3.1', '4.1.2'], 'failed'),
('aria_05', 'Encontrei estados e propriedades ARIA com valores permitidos', '<p>As especificações HTML e ARIA definem os estados e propriedades ARIA que são permitidos nos diferentes elementos HTML. Garanta que apenas usa estados e propriedades permitidos, caso contrário o seu código não irá produzir o efeito desejado.</p>', 'true', 'all', 'ariaStPermitted', 10, 'A', 1, ['1.3.1', '4.1.2'], 'passed'),
('aria_06', 'Encontrei estados e propriedades ARIA com valores não permitidos', '<p>As especificações HTML e ARIA definem os estados e propriedades ARIA que são permitidos nos diferentes elementos HTML. Garanta que apenas usa estados e propriedades permitidos, caso contrário o seu código não irá produzir o efeito desejado.</p>', 'fals', 'all', 'ariaStNotPermitted', 1, 'A', 1, ['1.3.1', '4.1.2'], 'failed'),
('aria_07', 'Encontrei atributos ARIA bem definidos', '<p>A especificação ARIA define o conjunto de atributos que podem ser usados. Se usar atributos que não estão definidos na especificação, eles não irão funcionar.</p>', 'true', 'all', 'ariaAtribDefined', 10, 'A', 1, ['1.3.1', '4.1.2'], 'passed'),
('aria_08', 'Encontrei atributos ARIA mal definidos', '<p>A especificação ARIA define o conjunto de atributos que podem ser usados. Se usar atributos que não estão definidos na especificação, eles não irão funcionar.</p>', 'fals', 'all', 'ariaAtribNotDefined', 1, 'A', 1, ['1.3.1', '4.1.2'], 'failed'),
('audio_video_01', 'Elementos <code>audio</code> e <code>video</code> não tocam automaticamente', '<p>Elementos <code>&lt;audio&gt;</code> e <code>&lt;video&gt;</code> que tocam automaticamente podem prejudicar utilizadores de leitor de ecrã ao sobreporem o som. Por isso, estes elementos não devem tocar automaticamente, ou, caso toquem, devem ter áudio inferior a 3 segundos, ou possuir um mecanismo que permita interromper ou silenciar o áudio.</p>', 'true', 'all', 'audioAvoidsAutoPlay', 10, 'A', 1, ['1.4.2'], 'passed'),
('audio_video_02', 'Elementos <code>audio</code> e <code>video</code> que tocam automaticamente', '<p>Elementos <code>&lt;audio&gt;</code> e <code>&lt;video&gt;</code> que tocam automaticamente podem prejudicar utilizadores de leitor de ecrã ao sobreporem o som. Por isso, estes elementos não devem tocar automaticamente, ou, caso toquem, devem ter áudio inferior a 3 segundos, ou possuir um mecanismo que permita interromper ou silenciar o áudio.</p>', 'fals', 'all', 'audioAutoPlay', 1, 'A', 1, ['1.4.2'], 'failed'),
('autocomplete_01', 'Atributos autocomplete válidos', '<p>As regras de preenchimento dos atributos autocomplete são definidas na especificação HTML. Garante que obedece as estas regras, caso contrário, os elementos não serão preenchidos automaticamente.</p>', 'true', 'all', 'autoCmpltValid', 10, 'A', 1, ['1.3.5'], 'passed'),
('autocomplete_02', 'Atributos autocomplete inválidos', '<p>As regras de preenchimento dos atributos autocomplete são definidas na especificação HTML. Garante que obedece as estas regras, caso contrário, os elementos não serão preenchidos automaticamente.</p>', 'fals', 'all', 'autoCmpltNotValid', 1, 'A', 1, ['1.3.5'], 'failed'),
('blink_02', 'Valores <code>&lt;blink&gt;</code> em CSS provocam cintilação de partes do conteúdo', '<p>Alguns grupos de utilizadores, particularmente os que têm perturbações que causam défices de atenção, encontram no conteúdo cintilante elementos de distracção, dificultando-lhes a capacidade de concentração nas restantes partes do conteúdo da página Web.</p>', 'true', 'all', 'cssBlink', 1, 'A', 0.9, ['2.2.2'], 'failed'),
('br_01', 'Sequências de 3 ou mais elementos <code>&lt;br&gt;</code>', '<p>Se o conteúdo que identifiquei é, na verdade, uma lista de opções então use a marcação estrutural correta (i.e. <code>&lt;ul&gt;</code>, <code>&lt;ol&gt;</code>).</p>', 'decr', 'all', 'brSec', 3, 'A', 0.7, ['1.3.1'], 'failed'),
('button_01', '<code>button</code> com nome acessível não vazio', '<p>Os elementos <code>&lt;button&t;</code> são elementos com os quais o utilizador pode interagir. Por isso, devem ter nome acessível de modo a que utilizadores de tecnologias de apoio saibam qual o seu propósito.</p>', 'true', 'button', 'buttonAname', 10, 'A', 1, ['4.1.2'], 'passed'),
('button_02', '<code>button</code> com nome acessível vazio', '<p>Os elementos <code>&lt;button&t;</code> são elementos com os quais o utilizador pode interagir. Por isso, devem ter nome acessível de modo a que utilizadores de tecnologias de apoio saibam qual o seu propósito.</p>', 'prop', 'button', 'buttonNotAname', 1, 'A', 1, ['4.1.2'], 'failed'),
('color_01', 'Encontrei páginas em que as regras de CSS que não especificam a cor da letra ou a cor do fundo', '<p>Não é necessário que a cor da letra e a cor do fundo estejam definidos na mesma regra de CSS mas é recomendável que assim seja. Esta é a única forma de garantir ao utilizador a obtenção do contraste desejado.</p>', 'true', 'all', 'colorFgBgNo', 3, 'AA', 0.9, ['1.4.3', '1.4.6', '1.4.8'], 'warning'),
('color_02', 'Encontrei páginas em que as combinações de cor cujas relações de contraste são menores que 4.5:1 para texto normal ou 3:1 para texto grande', '<p>De acordo com o critério de sucesso 1.4.3, o rácio 3 para 1 corresponde ao contraste mínimo para texto "em tamanho grande" (18 pt ou 14 pt negrito, ou maior). Recordo que para tamanho de letra normal o rácio mínimo é de 4,5 para 1.</p>', 'decr', 'all', 'colorContrast', 1, 'AA', 1, ['1.4.3'], 'failed'),
('color_02b', 'Encontrei combinações de cores cujo rácio de contraste cumpre o rácio de contraste mínimo permitido pelas WCAG', '<p>De acordo com o critério de sucesso 1.4.3, o rácio 3 para 1 corresponde ao contraste mínimo para texto "em tamanho grande" (18 pt ou 14 pt negrito, ou maior). Recordo que para tamanho de letra normal o rácio mínimo é de 4,5 para 1.</p>', 'true', 'all', 'colorContrastOk', 10, 'AA', 1, ['1.4.3'], 'passed'),
('css_01', 'Encontrei páginas em que as CSS especificam um espaçamento entre linhas inferior a 1.5', '<p>Muitas pessoas com incapacidades cognitivas têm dificuldade em acompanhar as linhas do texto quando o texto se apresenta com um espaçamento simples. Usar um espaçamento entre 1,5 e 2, facilita-lhes a passagem entre linhas.</p>', 'decr', 'all', 'lineHeightNo', 3, 'AA', 1, ['1.4.8', '1.4.12'], 'warning'),
('css_02', 'Encontrei a propriedade de CSS overflow', '<p>Ao ampliar a página a dimensão relativa do texto e dos seus contentores pode mudar o que faz com que estes possam necessitar de mais espaço para apresentar o mesmo texto. A propriedade CSS <code>overflow</code> determina como os contentores se ajustam. Alguns dos seus valores podem resultar no texto ser cortado.</p>', 'true', 'all', 'overflow', 10, 'AA', 1, ['1.4.4'], 'warning'),
('ehandler_02', 'Encontrei páginas em que não se usam manipuladores de eventos redundantes', '<p>Deve assegurar que os eventos de javascript são ativados não só através do rato mas também do teclado. Verifique os pares de manipuladores: mousedown/keydown, mouseup/keyup, mouseover/focus, mouseout/blur. Nota: O AccessMonitor não verifica o par onclick / onkeypress porque considera que os browsers suportam o onclick também quando se usa apenas o teclado.</p>', 'prop', 'ehandler', 'ehandBothNo', 1, 'A', 1, ['2.1.1', '2.1.3'], 'failed'),
('ehandler_03', 'Encontrei páginas com manipuladores de eventos redundantes', '<p>Deve assegurar que os eventos de javascript são ativados não só através do rato mas também do teclado. Verifique os pares de manipuladores: mousedown/keydown, mouseup/keyup, mouseover/focus, mouseout/blur. Nota: O AccessMonitor não verifica o par onclick / onkeypress porque considera que os browsers suportam o onclick também quando se usa apenas o teclado. Este teste só é classificado correto quando não existem erros nos outros testes de manipulares verificados.</p>', 'true', 'ehandler', 'ehandBoth', 10, 'A', 0.9, ['2.1.1', '2.1.3'], 'passed'),
('ehandler_04', 'Encontrei páginas com manipuladores de eventos associados a elementos não interativos', '<p>Os elementos genéricos como <code>&lt;div&gt;</code> e <code>&lt;span&gt;</code> não têm um papel pré-definido. Quando se faz uso destes elementos genéricos para criar controlos de interface de utilizador em HTML, as tecnologias de apoio não dispõem de informação suficiente para descrever e interagir com os controlos, nomeadamente se não se definir um "role" (papel) com técnicas de ARIA.</p>', 'prop', 'ehandler', 'ehandTagNo', 1, 'A', 0.8, ['4.1.2'], 'failed'),
('element_01', 'Elementos na ordem de foco sequencial', '<p>O foco visível permite distinguir quando é os elementos na ordem de foco sequencial recebem o foco. Verifique que todos os elementos na ordem de foco sequencial têm um indicador de foco visível quando recebem o foco.</p>', 'true', 'all', 'seqFocus', 10, 'AA', 1, ['2.4.7'], 'warning'),
('element_02', 'Elementos com o atributo aria-hidden sem conteúdo tocável', '<p>Os elementos com o atributo aria-hidden são escondidos das tecnologias de apoio. Se forem focáveis por teclado, quando forem focados os utilizadores de tecnologias de apoio não recebem informação sobre esses elementos.</p>', 'true', 'all', 'elementDec', 10, 'A', 1, ['4.1.2'], 'passed'),
('element_03', 'Elementos com o atributo aria-hidden com conteúdo focável', '<p>Os elementos com o atributo aria-hidden são escondidos das tecnologias de apoio. Se forem focáveis por teclado, quando forem focados os utilizadores de tecnologias de apoio não recebem informação sobre esses elementos.</p>', 'fals', 'all', 'elementNotDec', 1, 'A', 1, ['4.1.2'], 'failed'),
('element_04', 'Elementos marcados como decorativos', '<p>Os elementos decorativos não têm conteúdo informativo que deve ser apresentado aos utilizadores. Assim, estes elementos não devem ser expostos às Tecnologias de Apoio, para que não sejam apresentados aos seus utilizadores.</p>', 'true', 'all', 'elementHiddenFocus', 10, 'A', 1, ['4.1.2'], 'passed'),
('element_05', 'Elementos marcados como decorativos e expostos a tecnologias de apoio', '<p>Os elementos decorativos não têm conteúdo informativo que deve ser apresentado aos utilizadores. Assim, estes elementos não devem ser expostos às Tecnologias de Apoio, para que não sejam apresentados aos seus utilizadores.</p>', 'fals', 'all', 'elementNotHiddenFocus', 1, 'A', 1, ['4.1.2'], 'failed'),
('element_06', 'Elementos com atributo lang válido', '<p>Quando existem mudanças na linguagem do documento, estas devem ser identificadas recorrendo ao atributo lang.</p>', 'true', 'all', 'elementLang', 10, 'AA', 1, ['3.1.2'], 'passed'),
('element_07', 'Elementos com atributo lang inválido', '<p>Quando existem mudanças na linguagem do documento, estas devem ser identificadas recorrendo ao atributo lang.</p>', 'fals', 'all', 'elementNotLang', 3, 'AA', 1, ['3.1.2'], 'failed'),
('element_08', 'Elementos com descendentes decorativos', '<p>Elementos com um papel semântico que confere aos seus descendentes um papel decorativo, não devem possuir conteúdo focável, pois este conteúdo, quando for focado, não será apresentado às Tecnologias de Apoio.</p>', 'true', 'all', 'elementPresentChildrenNoFocus', 10, 'A', 1, ['4.1.2'], 'passed'),
('element_09', 'Elementos com descendentes decorativos focáveis', '<p>Elementos com um papel semântico que confere aos seus descendentes um papel decorativo, não devem possuir conteúdo focável, pois este conteúdo, quando for focado, não será apresentado às Tecnologias de Apoio.</p>', 'fals', 'all', 'elementPresentChildrenFocus', 1, 'A', 1, ['4.1.2'], 'failed'),
('element_10', 'Elementos com papel semântico explícito', '<p>Quando se define explicitamente o papel semântico de um elemento é necessário garantir que todos os estados e propriedades necessários ao funcionamento correto desse papel semântico com Tecnologias de Apoio foram definidos.</p>', 'true', 'all', 'elementRole', 10, 'A', 1, ['4.1.2', '1.3.1'], 'passed'),
('field_01', 'Encontrei páginas com elementos <fieldset> sem descrição', '<p>Os controlos de formulário podem ser agrupados, de acordo com a sua afinidade, através do elemento <code>&lt;fieldset&gt;</code>. O primeiro elemento dentro do <code>&lt;fieldset&gt;</code> deve ser o <code>&lt;legend&gt;</code>, o qual serve de etiqueta ou descrição para o agrupamento.</p>', 'true', 'all', 'fieldLegNo', 4, 'A', 1, ['1.3.1', '3.3.2'], 'failed'),
('field_02', 'Encontrei páginas com elementos <fieldset> fora do elemento <form>', '<p>Os controlos de formulário podem ser agrupados, de acordo com a sua afinidade, através do elemento <code>&lt;fieldset&gt;</code>. O primeiro elemento dentro do <code>&lt;fieldset&gt;</code> deve ser o <code>&lt;legend&gt;</code>, o qual serve de etiqueta ou descrição para o agrupamento.</p>', 'decr', 'all', 'fieldNoForm', 3, 'A', 0.9, ['1.3.1', '3.3.2'], 'failed'),
('focus_01', 'Encontrei páginas em que o Javascript é usado para remover o foco do campo', '<p>Percorra os campos de edição e verifique se o foco é inibido por técnicas de programação. Ao retirar o foco do conteúdo, este deixa de ser operável por quem usa apenas teclado para navegar.</p>', 'true', 'all', 'focusBlur', 3, 'A', 0.8, ['2.1.1', '2.4.7', '3.2.1'], 'failed'),
('font_01', 'Encontrei páginas com elementos ou atributos HTML que controlam a apresentação visual do texto', '<p>Esta prática está obsoleta. Em vez dela, deve usar as CSS para controlar a apresentação visual do texto. Quando este erro surge é porque está a usar dentro do elemento <code>&lt;body&gt;</code> da página os elementos: b, basefont, font, i, s, strike, u, ou os atributos: text, vlink, alink, link.</p>', 'decr', 'all', 'fontHtml', 3, 'AA', 1, ['1.3.1', '1.4.4', '1.4.5', '1.4.9'], 'failed'),
('font_02', 'Encontrei páginas em que o tamanhos de letra está incorretamente definido com unidades de medida absolutas', '<p>Quando o tamanho do texto está expresso em unidades absolutas há browsers que terão dificuldade em ampliar o texto.</p>', 'prop', 'fontValues', 'fontAbsVal', 3, 'AA', 1, ['1.4.4'], 'failed'),
('form_01a', 'Encontrei páginas em que todos os formulários têm um botão para submeter os dados', '<p>Depois de preenchido, é necessário submeter os dados do formulário ao servidor. Essa é a função do botão submeter ou submit button.</p>', 'fals', 'form', 'formSubmit', 10, 'A', 1, ['3.2.2'], 'passed'),
('form_01b', 'Encontrei páginas em os formulários não têm um botão para submeter os dados', '<p>Depois de preenchido, é necessário submeter os dados do formulário ao servidor. Essa é a função do botão submeter ou submit button.</p>', 'prop', 'form', 'formSubmitNo', 3, 'A', 0.9, ['3.2.2'], 'failed'),
('frame_01', 'Encontrei páginas com elementos frame sem atributo title ou cujo atributo title está vazio', '<p>As molduras (frame) são janelas onde é possível visualizar conteúdo proveniente de outro servidor. É importante identificar convenientemente essas molduras. Use o atributo title para o efeito!</p>', 'prop', 'frame', 'frameTitleNo', 3, 'A', 1, ['2.4.1', '4.1.2'], 'failed'),
('headers_01', 'Atributos <code>headers</code> identificam células na mesma tabela', '<p>Em tabelas de dados complexas (com cabeçalhos em várias linhas) é importante associar explicitamente as células de dados aos vários cabeçalhos que lhe dão contexto. Essa associação é feita com o atributo headers.</p>', 'true', 'headers', 'headerAtt', 10, 'A', 1, ['1.3.1'], 'passed'),
('headers_02', 'Atributos <code>headers</code> identificam células noutra tabela', '<p>Em tabelas de dados complexas (com cabeçalhos em várias linhas) é importante associar explicitamente as células de dados aos vários cabeçalhos que lhe dão contexto. Essa associação é feita com o atributo headers.</p>', 'prop', 'headers', 'headerAttNot', 3, 'A', 1, ['1.3.1'], 'failed'),
('heading_01', 'Encontrei paginas em que os cabeçalhos têm nome acessivél', '<p>As páginas Web devem ser marcadas com uma estrutura hierarquizada de títulos e subtítulos. Cada página deve ter, no mínimo, um título de nível 1. O nível 2 deve marcar as secções e o nível 3 as subsecções destas. Esta mesma lógica deve ser aplicada até às subsecções de nível 6.</p>', 'true', 'hx', 'hxHasAName', 10, 'A', 1, ['1.3.1'], 'passed'),
('heading_02', 'Encontrei paginas em que os cabeçalhos não têm nome acessivél', '<p>As páginas Web devem ser marcadas com uma estrutura hierarquizada de títulos e subtítulos. Cada página deve ter, no mínimo, um título de nível 1. O nível 2 deve marcar as secções e o nível 3 as subsecções destas. Esta mesma lógica deve ser aplicada até às subsecções de nível 6.</p>', 'prop', 'hx', 'hxWithoutAName', 1, 'A', 1, ['1.3.1'], 'failed'),
('heading_03', 'Apenas um elemento <code>h1</code>', '<p>As páginas Web devem ser marcadas com uma estrutura hierarquizada de títulos e subtítulos. Cada página deve ter, no mínimo, um título de nível 1. O nível 2 deve marcar as secções e o nível 3 as subsecções destas. Esta mesma lógica deve ser aplicada até às subsecções de nível 6.</p>', 'true', 'h1', 'onlyOneh1', 10, 'A', 1, ['1.3.1'], 'passed'),
('heading_04', 'Zero ou mais de um elemento <code>h1</code>', '<p>As páginas Web devem ser marcadas com uma estrutura hierarquizada de títulos e subtítulos. Cada página deve ter, no mínimo, um título de nível 1. O nível 2 deve marcar as secções e o nível 3 as subsecções destas. Esta mesma lógica deve ser aplicada até às subsecções de nível 6.</p>', 'fals', 'h1', 'notOneh1', 1, 'A', 1, ['1.3.1'], 'failed'),
('hx_01a', 'Encontrei páginas sem cabeçalhos', '<p>As páginas Web devem ser marcadas com uma estrutura hierarquizada de títulos e subtítulos. Cada página deve ter, no mínimo, um título de nível 1. O nível 2 deve marcar as secções e o nível 3 as subsecções destas. Esta mesma lógica deve ser aplicada até às subsecções de nível 6.</p>', 'fals', 'all', 'hxNone', 3, 'A', 1, ['1.3.1'], 'failed'),
('hx_01b', 'Encontrei páginas em que se usam cabeçalhos', '<p>As páginas Web devem ser marcadas com uma estrutura hierarquizada de títulos e subtítulos. Cada página deve ter, no mínimo, um título de nível 1. O nível 2 deve marcar as secções e o nível 3 as subsecções destas. Esta mesma lógica deve ser aplicada até às subsecções de nível 6.</p>', 'true', 'all', 'hx', 10, 'AAA', 0.9, ['1.3.1', '2.4.10'], 'warning'),
('hx_01c', 'Encontrei páginas em que não há um cabeçalho principal marcado (H1)', '<p>As páginas Web devem ser marcadas com uma estrutura hierarquizada de títulos e subtítulos. Cada página deve ter, no mínimo, um título de nível 1. O nível 2 deve marcar as secções e o nível 3 as subsecções destas. Esta mesma lógica deve ser aplicada até às subsecções de nível 6.</p>', 'fals', 'hx', 'h1', 4, 'AAA', 1, ['1.3.1', '2.4.10'], 'failed'),
('hx_02', 'Encontrei páginas em que há cabeçalhos cujo conteúdo é apenas uma imagem sem o equivalente alternativo em texto', '<p>Os cabeçalhos devem ser descritivos mas ao mesmo tempo sucintos. O seu conteúdo nunca, em caso algum, deve ser nulo - é o que está a acontecer neste caso.</p>', 'true', 'hx', 'hxNo', 3, 'AA', 1, ['2.4.6'], 'failed'),
('hx_03', 'Encontrei páginas em que a sequência hierárquica dos níveis de cabeçalho é violada', '<p>As páginas Web devem ser marcadas com uma estrutura hierarquizada de títulos e subtítulos. Cada página deve ter, no mínimo, um título de nível 1. O nível 2 deve marcar as secções e o nível 3 as subsecções destas. Esta mesma lógica deve ser aplicada até às subsecções de nível 6.</p>', 'prop', 'hx', 'hxSkip', 3, 'AAA', 1, ['1.3.1', '2.4.10'], 'failed'),
('id_01', 'Encontrei páginas sem atributos id repetidos', '<p>É conhecido que ter o mesmo atributo <code>id</code> em diferentes elementos causa problemas às tecnologias de apoio. Estes problemas podem ser evitados se garantir que na mesma página não se usam valores de <code>id</code> duplicados.</p>', 'true', 'id', 'idAtt', 10, 'A', 1, ['4.1.1'], 'passed'),
('id_02', 'Encontrei páginas com atributos id repetidos', '<p>É conhecido que ter o mesmo atributo <code>id</code> em diferentes elementos causa problemas às tecnologias de apoio. Estes problemas podem ser evitados se garantir que na mesma página não se usam valores de <code>id</code> duplicados.</p>', 'prop', 'id', 'idAttNot', 3, 'A', 1, ['4.1.1'], 'failed'),
('iframe_01', 'Encontrei páginas com elementos <iframe> sem o atributo title', '<p>As molduras (frame) são janelas onde é possível visualizar conteúdo proveniente de outro servidor. É importante identificar convenientemente essas molduras. Use o atributo title para o efeito!</p>', 'prop', 'iframe', 'iframeTitleNo', 3, 'A', 1, ['2.4.1', '4.1.2'], 'failed'),
('iframe_02', 'Encontrei páginas com elementos <iframe> com o mesmo nome acessível que apresentam o mesmo recurso', '<p>O nome acessível de um elemento <code>iframe</code> permite aos utilizadores de Tecnologias de Apoio saber o propósito do conteúdo desse elemento. Verifique que quando dois elementos <code>iframe</code> têm o mesmo nome acessível, o seu conteúdo serve o mesmo propósito.</p>', 'true', 'iframeSame', 'iframeSameAName', 10, 'A', 1, ['4.1.2'], 'passed'),
('iframe_03', 'Encontrei páginas com elementos <iframe> com o mesmo nome acessível', '<p>O nome acessível de um elemento <code>iframe</code> permite aos utilizadores de Tecnologias de Apoio saber o propósito do conteúdo desse elemento. Verifique que quando dois elementos <code>iframe</code> têm o mesmo nome acessível, o seu conteúdo serve o mesmo propósito.</p>', 'prop', 'iframeSame', 'iframeSameANameDiferent', 3, 'A', 1, ['4.1.2'], 'warning'),
('iframe_04', 'Encontrei páginas com elementos <iframe> com tabindex negativo e sem elementos interativos', '<p>Verifique se o equivalente alternativo em texto existente nos elementos svg serve informação ou função igual à desempenhada pela imagem na página.</p>', 'true', 'all', 'iframeNegTabIndex', 10, 'A', 1, ['2.1.1'], 'passed'),
('iframe_05', 'Encontrei páginas com elementos <iframe> com tabindex negativo e com elementos interativos', '<p>Verifique se o equivalente alternativo em texto existente nos elementos svg serve informação ou função igual à desempenhada pela imagem na página.</p>', 'fals', 'all', 'iframeNegTabIndexNot', 4, 'A', 1, ['2.1.1'], 'failed'),
('img_01a', 'Encontrei páginas em que todas as imagens têm um atributo com um equivalente alternativo em texto', '<p>Verifique se o equivalente alternativo em texto existente nas imagens serve informação ou função igual à desempenhada pela imagem na página.</p>', 'fals', 'img', 'imgAlt', 10, 'A', 0.9, ['1.1.1'], 'passed'),
('img_01b', 'Encontrei páginas com imagens sem um atributo com um equivalente alternativo em texto', '<p>Verifique se o equivalente textual alternativo existente nos botões gráficos serve informação ou função igual à desempenhada pelo botão gráfico na página.</p>', 'prop', 'img', 'imgAltNo', 3, 'A', 1, ['1.1.1'], 'failed'),
('img_02', 'Encontrei páginas com imagens com alt="" (alt vazio; imagem marcada como decorativa)', '<p>O uso de textos alternativos vazios em HTML é uma prática comum para imagens classificadas como sendo decorativas. Todavia, todas as imagens classificadas como decorativas devem ser afixadas via CSS e não via HTML.</p>', 'prop', 'img', 'imgAltNull', 8, 'A', 1, ['1.1.1'], 'warning'),
('img_03', 'Encontrei páginas com imagens com um atributo que não serve de equivalente alternativo em texto', '<p>No atributo <code>&lt;alt&gt;</code> do elemento <code>&lt;img&gt;</code> encontrei o nome do ficheiro imagem ou um dos seguintes valores: "img", "image", "spacer", "space", "picture", "alt", "alttext", "imagen", "imagem", "foto", "photo", ou uma das seguintes extensões de imagem .jpg, .jpeg, .gif, .png. Nenhum dos valores referidos acima serve de equivalente textual alternativo.</p>', 'decr', 'img', 'imgAltNot', 3, 'A', 1, ['1.1.1', '1.2.1'], 'failed'),
('img_04', 'Encontrei páginas com imagens com mais de 100 caracteres no atributo que serve de equivalente alternativo em texto', '<p>O atributo longdesc tem de ser composto por um URI que aponte a localização onde se encontra a descrição longa - pode ser outra página ou uma âncora na mesma página.</p>', 'prop', 'img', 'imgAltLong', 5, 'A', 0.9, ['1.1.1'], 'warning'),
('inp_img_01a', 'Encontrei páginas em que todos os botões gráficos usam o atributo alt', '<p>O elemento <code>&lt;input&gt;</code> é utilizado para criar muitos tipos de controlos de formulário. Apesar das DTDs de HTML e XHTML permitirem o uso do atributo alt em todos os seus elementos, o atributo alt deve ser usado, no caso do elemento <code>&lt;input&gt;</code>, apenas nos botões gráficos.</p>', 'fals', 'inpImg', 'inpImgAltYes', 10, 'A', 0.9, ['1.1.1', '4.1.2'], 'passed'),
('inp_img_01b', 'Encontrei páginas sem atributo alt nos botões gráficos', '<p>Verifique se o equivalente textual alternativo existente nos botões gráficos serve informação ou função igual à desempenhada pelo botão gráfico na página.</p>', 'prop', 'inpImg', 'inpImgAltNo', 1, 'A', 1, ['1.1.1', '4.1.2'], 'failed'),
('input_01', 'Encontrei páginas em que os controlos de formulário não têm o elemento <label> associado e não têm o atributo title associado', '<p>Para preencher os campos de edição, os utilizadores precisam que os mesmos estejam identificados. Pode ser uma identificação explicita (marcada no código) ou implícita (geralmente derivada da posição relativa). Explicitamente pode ser feita pelo elemento <code>&lt;label&gt;</code> ou pelo atributo title do elemento <code>&lt;input&gt;</code>.</p>', 'prop', 'inputLabel', 'inputIdTitleNo', 3, 'A', 1, ['1.1.1', '1.3.1', '3.3.2', '4.1.2'], 'failed'),
('input_02', 'Encontrei páginas em que os controlos de formulário não têm um nome acessível', '<p>Os elementos <code>&lt;label&gt;</code> associados aos elementos <code>&lt;input&gt;</code> permitem aos utilizadores de Tecnologias de Apoio identificar a etiqueta que contextualiza um campo de edição. A associação explicita é feita pelo par de atributos id e for, respetivamente, dos elementos <code>&lt;input&gt;</code> e <code>&lt;label&gt;</code>.</p>', 'prop', 'label', 'inputLabelNo', 3, 'A', 0.8, ['1.1.1', '1.3.1', '3.3.2', '4.1.2'], 'warning'),
('input_02b', 'Encontrei páginas em que todos os controlos de formulário têm um nome acessível', '<p>Os elementos <code>&lt;label&gt;</code> associados aos elementos <code>&lt;input&gt;</code> permitem aos utilizadores de Tecnologias de Apoio identificar a etiqueta que contextualiza um campo de edição. A associação explicita é feita pelo par de atributos id e for, respetivamente, dos elementos <code>&lt;input&gt;</code> e <code>&lt;label&gt;</code>.</p>', 'fals', 'inputLabel', 'inputLabel', 10, 'A', 0.7, ['1.1.1', '1.3.1', '3.3.2', '4.1.2'], 'passed'),
('input_03', 'Encontrei páginas cujos elementos <input> têm o atributo alt mas não são botões gráficos', '<p>O elemento <code>&lt;input&gt;</code> é utilizado para criar muitos tipos de controlos de formulário. Apesar das DTDs de HTML e XHTML permitirem o uso do atributo alt em todos os seus elementos, o atributo alt deve ser usado, no caso do elemento <code>&lt;input&gt;</code>, apenas nos botões gráficos.</p>', 'true', 'all', 'inputAltNo', 5, 'A', 1, ['1.1.1'], 'failed'),
('justif_txt_01', 'Encontrei páginas com o texto justificado via HTML', '<p>Algumas pessoas com baixa visão e algumas pessoas com incapacidades cognitivas têm grande dificuldade em lidar com blocos de texto que se encontram justificados.</p>', 'decr', 'all', 'justifiedTxt', 5, 'AAA', 1, ['1.4.8'], 'failed'),
('justif_txt_02', 'Encontrei páginas com o texto justificado via CSS', '<p>Algumas pessoas com baixa visão e algumas pessoas com incapacidades cognitivas têm grande dificuldade em lidar com blocos de texto que se encontram justificados.</p>', 'decr', 'all', 'justifiedCss', 5, 'AAA', 0.9, ['1.4.8'], 'warning'),
('label_01', 'Encontrei páginas com elementos interativos com conteúdo textual que está presente no seu nome acessível', '<p>Os utilizadores de sistemas de reconhecimento de fala, tipicamente dizem o nome de um comando seguido de uma referência ao texto de um elemento (p.ex. selecionar pesquisa, para ativar o botão com o texto “pesquisa”). Os sistemas de reconhecimento de fala usam o nome acessível do elemento para o associar ao comando do utilizador. Assim, se o nome acessível não incluir o texto visível, estes sistemas não conseguirão fazer a associação necessária ao seu funcionamento.</p>', 'true', 'all', 'labelAName', 10, 'A', 1, ['2.5.3'], 'passed'),
('label_02', 'Encontrei páginas com elementos <label> que não estão visíveis ou estão incorretamente posicionados', '<p>As etiquetas devem ser posicionadas imediatamente antes dos campos. As etiquetas para os campos do tipo listas de verificação (checkbox) e do tipo botões de rádio (radio) devem ser posicionadas logo após os campos.</p>', 'decr', 'all', 'labelPosNo', 3, 'A', 0.9, ['1.3.1', '3.3.2'], 'failed'),
('label_02b', 'Encontrei páginas com elementos <label> cujo posicionamento é ambíguo', '<p>As etiquetas devem ser posicionadas imediatamente antes dos campos. As etiquetas para os campos do tipo listas de verificação (checkbox) e do tipo botões de rádio (radio) devem ser posicionadas logo após os campos.</p>', 'decr', 'all', 'labelPosWarn', 7, 'A', 0.7, ['1.3.1', '3.3.2'], 'warning'),
('label_03', 'Encontrei páginas com elementos interativos com conteúdo textual que não está presente no seu nome acessível', '<p>Os utilizadores de sistemas de reconhecimento de fala, tipicamente dizem o nome de um comando seguido de uma referência ao texto de um elemento (p.ex. selecionar pesquisa, para ativar o botão com o texto “pesquisa”). Os sistemas de reconhecimento de fala usam o nome acessível do elemento para o associar ao comando do utilizador. Assim, se o nome acessível não incluir o texto visível, estes sistemas não conseguirão fazer a associação necessária ao seu funcionamento.</p>', 'fals', 'all', 'labelANameNot', 4, 'A', 1, ['2.5.3'], 'failed'),
('landmark_01', 'Elemento com semântica <code>banner</code> usado corretamente', '<p>Garanta que só há um elemento com a semântica de main na página. Elementos com esta semântica designam a parte principal da página e permitem que utilizadores de leitor de ecrã naveguem rapidamente para essa parte da página. Cada página só deve ter um conteúdo principal, independentemente de ser especificado usando HTML5 ou ARIA.</p>', 'true', 'all', 'bannerTopLevel', 10, 'AA', 1, ['1.3.1', '2.4.1'], 'passed'),
('landmark_02', 'Elemento com semântica <code>banner</code> dentro de elementos com outra semântica', '<p>Garanta que só há um elemento com a semântica de main na página. Elementos com esta semântica designam a parte principal da página e permitem que utilizadores de leitor de ecrã naveguem rapidamente para essa parte da página. Cada página só deve ter um conteúdo principal, independentemente de ser especificado usando HTML5 ou ARIA.</p>', 'fals', 'all', 'bannerNotTopLevel', 4, 'AA', 1, ['1.3.1', '2.4.1'], 'failed'),
('landmark_03', 'Elemento com semântica <code>complementary</code> usado corretamente', '<p>Garanta que só há um elemento com a semântica de main na página. Elementos com esta semântica designam a parte principal da página e permitem que utilizadores de leitor de ecrã naveguem rapidamente para essa parte da página. Cada página só deve ter um conteúdo principal, independentemente de ser especificado usando HTML5 ou ARIA.</p>', 'true', 'all', 'complementaryTopLevel', 10, 'AA', 1, ['1.3.1'], 'passed'),
('landmark_04', 'Elemento com semântica <code>complementary</code> dentro de elementos com outra semântica', '<p>Garanta que só há um elemento com a semântica de main na página. Elementos com esta semântica designam a parte principal da página e permitem que utilizadores de leitor de ecrã naveguem rapidamente para essa parte da página. Cada página só deve ter um conteúdo principal, independentemente de ser especificado usando HTML5 ou ARIA.</p>', 'fals', 'all', 'complementaryNotTopLevel', 4, 'AA', 1, ['1.3.1'], 'failed'),
('landmark_05', 'Elemento com semântica <code>contentinfo</code> usado corretamente', '<p>Garanta que só há um elemento com a semântica de main na página. Elementos com esta semântica designam a parte principal da página e permitem que utilizadores de leitor de ecrã naveguem rapidamente para essa parte da página. Cada página só deve ter um conteúdo principal, independentemente de ser especificado usando HTML5 ou ARIA.</p>', 'true', 'all', 'contentinfoTopLevel', 10, 'AA', 1, ['1.3.1'], 'passed'),
('landmark_06', 'Elemento com semântica <code>contentinfo</code> dentro de elementos com outra semântica', '<p>Garanta que só há um elemento com a semântica de main na página. Elementos com esta semântica designam a parte principal da página e permitem que utilizadores de leitor de ecrã naveguem rapidamente para essa parte da página. Cada página só deve ter um conteúdo principal, independentemente de ser especificado usando HTML5 ou ARIA.</p>', 'fals', 'all', 'contentinfoNotTopLevel', 4, 'AA', 1, [], 'failed'),
('landmark_07', 'Elemento com semântica <code>main</code> usado corretamente', '<p>Garanta que só há um elemento com a semântica de main na página. Elementos com esta semântica designam a parte principal da página e permitem que utilizadores de leitor de ecrã naveguem rapidamente para essa parte da página. Cada página só deve ter um conteúdo principal, independentemente de ser especificado usando HTML5 ou ARIA.</p>', 'true', 'all', 'mainTopLevel', 10, 'AA', 1, ['1.3.1'], 'passed'),
('landmark_08', 'Elemento com semântica <code>main</code> dentro de elementos com outra semântica', '<p>Garanta que só há um elemento com a semântica de main na página. Elementos com esta semântica designam a parte principal da página e permitem que utilizadores de leitor de ecrã naveguem rapidamente para essa parte da página. Cada página só deve ter um conteúdo principal, independentemente de ser especificado usando HTML5 ou ARIA.</p>', 'fals', 'all', 'mainNotTopLevel', 4, 'AA', 1, ['1.3.1'], 'failed'),
('landmark_09', 'Encontrei apenas um elemento com semântica <code>banner</code>', '<p>Garanta que só há um elemento com a semântica de main na página. Elementos com esta semântica designam a parte principal da página e permitem que utilizadores de leitor de ecrã naveguem rapidamente para essa parte da página. Cada página só deve ter um conteúdo principal, independentemente de ser especificado usando HTML5 ou ARIA.</p>', 'true', 'all', 'noDuplicateBanner', 10, 'AA', 1, ['1.3.1', '2.4.1'], 'passed'),
('landmark_10', 'Encontrei mais do que um elemento com semântica <code>banner</code>', '<p>Garanta que só há um elemento com a semântica de main na página. Elementos com esta semântica designam a parte principal da página e permitem que utilizadores de leitor de ecrã naveguem rapidamente para essa parte da página. Cada página só deve ter um conteúdo principal, independentemente de ser especificado usando HTML5 ou ARIA.</p>', 'fals', 'all', 'duplicateBanner', 4, 'AA', 1, ['1.3.1', '2.4.1'], 'failed'),
('landmark_11', 'Encontrei apenas um elemento com semântica <code>contentinfo</code>', '<p>Garanta que só há um elemento com a semântica de main na página. Elementos com esta semântica designam a parte principal da página e permitem que utilizadores de leitor de ecrã naveguem rapidamente para essa parte da página. Cada página só deve ter um conteúdo principal, independentemente de ser especificado usando HTML5 ou ARIA.</p>', 'true', 'all', 'noDuplicateContentinfo', 10, 'AA', 1, ['1.3.1'], 'passed'),
('landmark_12', 'Encontrei mais do que um elemento com semântica <code>contentinfo</code>', '<p>Garanta que só há um elemento com a semântica de main na página. Elementos com esta semântica designam a parte principal da página e permitem que utilizadores de leitor de ecrã naveguem rapidamente para essa parte da página. Cada página só deve ter um conteúdo principal, independentemente de ser especificado usando HTML5 ou ARIA.</p>', 'fals', 'all', 'duplicateContentinfo', 4, 'AA', 1, ['1.3.1'], 'failed'),
('landmark_13', 'Encontrei apenas um elemento com semântica <code>main</code>', '<p>Garanta que só há um elemento com a semântica de main na página. Elementos com esta semântica designam a parte principal da página e permitem que utilizadores de leitor de ecrã naveguem rapidamente para essa parte da página. Cada página só deve ter um conteúdo principal, independentemente de ser especificado usando HTML5 ou ARIA.</p>', 'true', 'all', 'noDuplicateMain', 10, 'AA', 1, ['1.3.1'], 'passed'),
('landmark_14', 'Encontrei mais do que um elemento com semântica <code>mais</code>', '<p>Garanta que só há um elemento com a semântica de main na página. Elementos com esta semântica designam a parte principal da página e permitem que utilizadores de leitor de ecrã naveguem rapidamente para essa parte da página. Cada página só deve ter um conteúdo principal, independentemente de ser especificado usando HTML5 ou ARIA.</p>', 'fals', 'all', 'duplicateMain', 4, 'AA', 1, [], 'failed'),
('lang_01', 'Encontrei páginas em que o idioma principal da página está corretamente marcado', '<p>O HTML apenas dispõe do atributo lang. O XHTML 1.1 apenas permite o  xml:lang. O XHTML 1.0 (como medida de transição) permite ambos os atributos. O XHTML servido como text/html utiliza os atributos lang e xml:lang do elemento html.</p>', 'true', 'all', 'lang', 10, 'A', 0.8, ['3.1.1'], 'warning'),
('lang_02', 'Encontrei páginas em que o idioma principal da página está incorretamente marcado', '<p>O HTML apenas dispõe do atributo lang. O XHTML 1.1 apenas permite o  xml:lang. O XHTML 1.0 (como medida de transição) permite ambos os atributos. O XHTML servido como text/html utiliza os atributos lang e xml:lang do elemento html.</p>', 'true', 'all', 'langCodeNo', 1, 'A', 1, ['3.1.1'], 'failed'),
('lang_03', 'Encontrei páginas com o atributo lang ou xml:lang em falta', '<p>O HTML apenas dispõe do atributo lang. O XHTML 1.1 apenas permite o  xml:lang. O XHTML 1.0 (como medida de transição) permite ambos os atributos. O XHTML servido como text/html utiliza os atributos lang e xml:lang do elemento html.</p>', 'true', 'all', 'langNo', 1, 'A', 1, ['3.1.1'], 'failed'),
('lang_04', 'Encontrei páginas em que os atributos lang e/ou xml:lang estão a ser utilizados de forma incorreta', '<p>O HTML apenas dispõe do atributo lang. O XHTML 1.1 apenas permite o  xml:lang. O XHTML 1.0 (como medida de transição) permite ambos os atributos. O XHTML servido como text/html utiliza os atributos lang e xml:lang do elemento html.</p>', 'true', 'all', 'langMatchNo', 1, 'A', 1, ['3.1.1'], 'failed'),
('layout_01a', 'Encontrei páginas em que não há elementos obsoletos a controlar a apresentação visual', '<p>Com o aparecimento das CSS todos os elementos de HTML usados para controlo de estilos da página ficaram obsoletos. Elementos como: b, big, blink, center, font, i, s, strike, u ficaram obsoletos - use CSS para os substituir</p>', 'fals', 'all', 'layoutElemNo', 10, 'A', 1, ['1.3.1'], 'passed'),
('layout_01b', 'Encontrei páginas em que se usam Elementos obsoletos para controlar a apresentação visual', '<p>Com o aparecimento das CSS todos os elementos de HTML usados para controlo de estilos da página ficaram obsoletos. Elementos como: b, big, blink, center, font, i, s, strike, u ficaram obsoletos - use CSS para os substituir</p>', 'decr', 'all', 'layoutElem', 1, 'A', 1, ['1.3.1'], 'failed'),
('layout_03', 'Encontrei páginas em que se usam unidades de medida abosulata na CSS para dimensionar a largura dos elementos', '<p>Amplie 200% o ecrã e verifique que todo o conteúdo é visível sem necessidade de efetuar varrimentos horizontais.</p>', 'decr', 'all', 'layoutFixed', 3, 'AA', 1, ['1.4.4', '1.4.8'], 'failed'),
('letter_01', 'Propriedade de CSS letter-spacing correta', '<p>Um espaçamento entre letras igual ou superior a 0,12 vezes o tamanho da fonte é importante para garantir que todos os utilizadores conseguem ler o texto. Os estilos CSS não devem impedir que os utilizadores aumentem o espaçamento entre letras se assim o entenderem.</p>', 'true', 'all', 'letterSpacing', 10, 'AA', 1, ['1.4.12'], 'passed'),
('letter_02', 'Propriedade de CSS letter-spacing com espaçamento incorreto', '<p>Um espaçamento entre letras igual ou superior a 0,12 vezes o tamanho da fonte é importante para garantir que todos os utilizadores conseguem ler o texto. Os estilos CSS não devem impedir que os utilizadores aumentem o espaçamento entre letras se assim o entenderem.</p>', 'decr', 'all', 'letterSpacingNot', 4, 'AA', 1, ['1.4.12'], 'failed'),
('link_01', 'Encontrei páginas em que os metadados <link> poderão servir para construir um sistema de navegação', '<p>Verifique se em cada cada um dos elementos <code>&lt;link&gt;</code> existentes no <code>&lt;head&gt;</code> da página, o href aponta um recurso apropriado.</p>', 'true', 'all', 'linkRel', 10, 'AA', 0.9, ['2.4.5', '2.4.8'], 'passed'),
('list_01', 'Encontrei páginas em que o item de lista <li> está marcado fora da lista', '<p>Se o conteúdo que identifiquei é, na verdade, uma lista de opções então use a marcação estrutural correta (i.e. <code>&lt;ul&gt;</code>, <code>&lt;ol&gt;</code>).</p>', 'decr', 'all', 'liNoList', 3, 'A', 1, ['1.3.1'], 'failed'),
('list_02', 'Encontrei páginas em que as listas só contêm itens de lista', '<p>Se o conteúdo que identifiquei é, na verdade, uma lista de opções então use a marcação estrutural correta (i.e. <code>&lt;ul&gt;</code>, <code>&lt;ol&gt;</code>).</p>', 'true', 'li', 'listCorrectly', 10, 'AA', 1, ['1.3.1'], 'passed'),
('list_03', 'Encontrei páginas com listas com elementos que não são itens de lista', '<p>Se o conteúdo que identifiquei é, na verdade, uma lista de opções então use a marcação estrutural correta (i.e. <code>&lt;ul&gt;</code>, <code>&lt;ol&gt;</code>).</p>', 'prop', 'li', 'listNotCorrectly', 4, 'AA', 1, ['1.3.1'], 'failed'),
('list_04', 'Encontrei páginas em que os itens de lista são apenas utilizados dentro de listas de descrição', '<p>Se uma lista de descrições conter elementos que não são itens da lista, ou se a ordem dos elementos não estiver correta, isto é, os elementos <dt> precederem os elementos <dd>, a lista estará mal formatada, e tecnologias de apoio não serão capazes de a apresentar corretamente.</p>', 'true', 'dd,dt', 'descListElement', 10, 'AAA', 1, ['3.1.3'], 'passed'),
('list_05', 'Encontrei páginas em que itens de lista são utilizados fora de listas de descrição', '<p>Se uma lista de descrições conter elementos que não são itens da lista, ou se a ordem dos elementos não estiver correta, isto é, os elementos <dt> precederem os elementos <dd>, a lista estará mal formatada, e tecnologias de apoio não serão capazes de a apresentar corretamente.</p>', 'prop', 'dd,dt', 'notDescListElement', 4, 'AAA', 1, ['3.1.3'], 'failed'),
('list_06', 'Encontrei páginas em que as listas de descrição têm os itens de lista ordenados corretamente', '<p>Se uma lista de descrições conter elementos que não são itens da lista, ou se a ordem dos elementos não estiver correta, isto é, os elementos <dt> precederem os elementos <dd>, a lista estará mal formatada, e tecnologias de apoio não serão capazes de a apresentar corretamente.</p>', 'true', 'dl', 'descList', 10, 'AAA', 1, ['3.1.3'], 'passed'),
('list_07', 'Encontrei páginas em que há listas de descrição com elementos que não são itens de lista ou não estão ordenados corretamente', '<p>Se uma lista de descrições conter elementos que não são itens da lista, ou se a ordem dos elementos não estiver correta, isto é, os elementos <dt> precederem os elementos <dd>, a lista estará mal formatada, e tecnologias de apoio não serão capazes de a apresentar corretamente.</p>', 'prop', 'dl', 'notDescList', 4, 'AAA', 1, ['3.1.3'], 'failed'),
('listitem_01', 'Encontrei itens de lista utilizados dentro de listas', '<p>Se o conteúdo que identifiquei é, na verdade, uma lista de opções então use a marcação estrutural correta (i.e. <code>&lt;ul&gt;</code>, <code>&lt;ol&gt;</code>).</p>', 'true', 'li', 'liSemantically', 10, 'AA', 1, ['1.3.1'], 'passed'),
('listitem_02', 'Encontrei itens de lista utilizados fora de listas', '<p>Se o conteúdo que identifiquei é, na verdade, uma lista de opções então use a marcação estrutural correta (i.e. <code>&lt;ul&gt;</code>, <code>&lt;ol&gt;</code>).</p>', 'prop', 'li', 'liNotSemantically', 4, 'AA', 1, ['1.3.1'], 'failed'),
('menuItem_01', 'Elementos com o papel semântico menuitem com nome acessível', '<p>Os elementos com o papel semântico <code>menuitem</code> correspondem a opções de navegação que o utilizador por selecionar. Se não tiverem nome acessível, os utilizadores de tecnologias de apoio não conseguirão saber a opção que estão a selecionar.</p>', 'true', 'menuItem', 'menuItemAName', 10, 'A', 1, ['4.1.2'], 'passed'),
('menuItem_02', 'Elementos com o papel semântico menuitem sem nome acessível', '<p>Os elementos com o papel semântico <code>menuitem</code> correspondem a opções de navegação que o utilizador por selecionar. Se não tiverem nome acessível, os utilizadores de tecnologias de apoio não conseguirão saber a opção que estão a selecionar.</p>', 'prop', 'menuItem', 'menuItemANameNot', 3, 'A', 1, ['4.1.2'], 'failed'),
('meta_01', 'Página reinicia automaticamente com elemento <code>meta http-equiv="refresh"</code>', '<p>O valor "refresh" deve ser usado com cuidado, uma vez que ele retira o controlo da página ao utilizador.</p>', 'true', 'all', 'metaRefresh', 1, 'A', 1, ['2.2.1', '2.2.4', '3.2.5'], 'warning'),
('meta_02', 'Página é redireccionada automaticamente com elemento <code>meta http-equiv="redirect"</code>', '<p>O valor “redirect" deve ser usado com cuidado, uma vez que ele retira o controlo da página ao utilizador.</p>', 'true', 'all', 'metaRedir', 1, 'A', 1, ['2.2.1', '2.2.4'], 'warning'),
('meta_03', 'Elemento <code>meta</code> não reinicia a página', '<p>Redirecionamentos implementados no cliente e que não acontecem instantaneamente, podem causar confusão aos utilizadores, pois estes não entendem a razão pela qual o redirecionamento aconteceu.</p>', 'true', 'all', 'metaRefresh', 10, 'AAA', 1, ['2.2.4'], 'passed'),
('meta_04', 'Elemento <code>meta</code> reinicia a página', '<p>Redirecionamentos implementados no cliente e que não acontecem instantaneamente, podem causar confusão aos utilizadores, pois estes não entendem a razão pela qual o redirecionamento aconteceu.</p>', 'fals', 'all', 'metaRefreshNot', 3, 'AAA', 1, ['2.2.4'], 'failed'),
('meta_05', 'Elemento <code>meta</code> com atributo viewport', '<p>Alguns browsers mais antigos de dispositivos móveis podem limitar a capacidade do utilizador fazer zoom na página, em função dos valores do atributo <code>viewport</code> do elemento <code>meta</code>. Apesar dos browsers mais recentes ignorarem estes atributos é sempre preferível não dar instruções que podem limitar as capacidades do utilizador.</p>', 'true', 'all', 'metaViewport', 10, 'AA', 1, ['1.4.4'], 'passed'),
('object_01', 'Encontrei páginas em que o elementos <object> tem um equivalente alternativo em texto', '<p>Alguns browsers mais antigos de dispositivos móveis podem limitar a capacidade do utilizador fazer zoom na página, em função dos valores do atributo <code>viewport</code> do elemento <code>meta</code>. Apesar dos browsers mais recentes ignorarem estes atributos é sempre preferível não dar instruções que podem limitar as capacidades do utilizador.</p>', 'true', 'object', 'objectAName', 10, 'A', 1, ['1.1.1'], 'passed'),
('object_02', 'Encontrei páginas em que o elementos <object> não tem um equivalente alternativo em texto', '<p>Alguns browsers mais antigos de dispositivos móveis podem limitar a capacidade do utilizador fazer zoom na página, em função dos valores do atributo <code>viewport</code> do elemento <code>meta</code>. Apesar dos browsers mais recentes ignorarem estes atributos é sempre preferível não dar instruções que podem limitar as capacidades do utilizador.</p>', 'prop', 'object', 'objectANameNot', 3, 'A', 1, ['1.1.1'], 'failed'),
('orientation_01', 'Elemento com propriedade CSS transform que não restringe a orientação da página', '<p>Alguns utilizadores precisam de usar os seus dispositivos numa orientação específica. Se a página impedir o seu conteúdo de se adaptar à orientação do dispositivo, esses utilizadores ficam impossibilitados de a usar corretamente.</p>', 'true', 'all', 'orientationCSS', 10, 'AA', 1, ['1.3.4'], 'passed'),
('orientation_02', 'Elemento com propriedade CSS transform que restringe a orientação da página', '<p>Alguns utilizadores precisam de usar os seus dispositivos numa orientação específica. Se a página impedir o seu conteúdo de se adaptar à orientação do dispositivo, esses utilizadores ficam impossibilitados de a usar corretamente.</p>', 'fals', 'all', 'orientationCSSNot', 4, 'AA', 1, ['1.3.4'], 'failed'),
('role_01', 'Elementos com atributo role válido', '<p>As Tecnologias de Apoio precisam de entender a semântica dos elementos de modo a poder transmitir corretamente aos seus utilizadores os conteúdos e possibilidades de interação disponibilizados pelos elementos de uma página. Quando definir explicitamente o <code>role</code> de um elemento, deve assegurar-se que o valor do <code>role</code> é um valor válido.</p>', 'true', 'all', 'roleValid', 10, 'AA', 1, ['1.3.4'], 'passed'),
('role_02', 'Elementos com atributo role inválido', '<p>As Tecnologias de Apoio precisam de entender a semântica dos elementos de modo a poder transmitir corretamente aos seus utilizadores os conteúdos e possibilidades de interação disponibilizados pelos elementos de uma página. Quando definir explicitamente o <code>role</code> de um elemento, deve assegurar-se que o valor do <code>role</code> é um valor válido.</p>', 'decr', 'all', 'roleValidNot', 3, 'AA', 1, ['1.3.4'], 'failed'),
('scope_01', 'Encontrei páginas em que se usa o atributo scope da tabela de dados de forma incorreta', '<p>O atributo scope identifica se uma célula constitui um cabeçalho de uma linha, de uma coluna, de um grupo de linhas ou de um grupo de colunas. Os valores row, col, rowgroup e colgroup identificam respectivamente os valores que o scope pode assumir.</p>', 'decr', 'table', 'scopeNo', 3, 'A', 1, ['1.3.1'], 'failed'),
('scrollable_01', 'Elementos com varrimento podem ser usados com teclado', '<p>Verifique se o equivalente alternativo em texto existente nos elementos svg serve informação ou função igual à desempenhada pela imagem na página.</p>', 'true', 'scrollable', 'scrollableAccess', 10, 'A', 1, ['2.1.1'], 'passed'),
('scrollable_02', 'Elementos com varrimento não podem ser usados com teclado', '<p>Verifique se o equivalente alternativo em texto existente nos elementos svg serve informação ou função igual à desempenhada pela imagem na página.</p>', 'prop', 'scrollable', 'scrollableAccessNot', 3, 'A', 1, ['2.1.1'], 'failed'),
('svg_01', 'Elemento <code>svg</code> com papel semântico explícito e nome acessível', '<p>Verifique se o equivalente alternativo em texto existente nos elementos svg serve informação ou função igual à desempenhada pela imagem na página.</p>', 'true', 'svg', 'svgAName', 10, 'A', 1, ['1.1.1'], 'passed'),
('svg_02', 'Elemento <code>svg</code> com papel semântico explícito sem nome acessível', '<p>Verifique se o equivalente alternativo em texto existente nos elementos svg serve informação ou função igual à desempenhada pela imagem na página.</p>', 'prop', 'svg', 'svgNotAName', 3, 'A', 1, ['1.1.1'], 'failed'),
('table_01', 'Encontrei páginas em que há tabelas sem cabeçalhos marcados (<th>) mas em que se usam o elemento <caption> e/ou o atributo summary', '<p>Desconfio que possa ter encontrado tabelas de dados sem a identificação dos cabeçalhos. Caso contrário, poderão ser tabelas layout e neste caso têm título, que deve ser retirado.</p>', 'prop', 'tableLayout', 'tableLayoutCaption', 3, 'A', 1, ['1.3.1'], 'warning'),
('table_02', 'Encontrei páginas em que há tabelas de dados sem o elemento <caption> ou atributo summary', '<p>Desconfio que possa ter encontrado tabelas de dados sem a identificação do título (<code>&lt;caption&gt;</code>).</p>', 'prop', 'tableData', 'tableDataCaption', 3, 'A', 1, ['1.3.1'], 'failed'),
('table_03', 'Encontrei páginas em que há tabelas com <caption> e summary iguais', '<p>Desconfio que possa ter encontrado tabelas de dados em que o conteúdo que se encontra no elemento <code>&lt;caption&gt;</code> é o mesmo que está no atributo summary.</p>', 'prop', 'table', 'tableCaptionSummary', 4, 'A', 1, ['1.3.1'], 'failed'),
('table_04', 'Encontrei páginas em que há tabelas dentro de outras tabelas', '<p>Ao linearizar as tabelas verifique se o conteúdo é percetível.</p>', 'prop', 'table', 'tableNested', 3, 'A', 0.9, ['1.3.2'], 'failed'),
('table_05a', 'Encontrei páginas em que há tabelas sem cabeçalhos marcados (<th>)', '<p>Apesar das WCAG não proibirem o uso de tabelas layout é recomendável não as usar. Se as tabelas em causa forem de dados então marque as células de cabeçalho convenientemente.</p>', 'decr', 'all', 'tableLayout', 4, 'A', 1, ['1.3.1'], 'failed'),
('table_06', 'Encontrei páginas em que há tabelas de dados complexas com células de dados sem o atributo headers', '<p>Em tabelas de dados complexas (com cabeçalhos em várias linhas) é importante associar explicitamente as células de dados aos vários cabeçalhos que lhe dão contexto. Essa associação é feita com o atributo headers.</p>', 'decr', 'tableComplex', 'tableComplexError', 4, 'A', 0.8, ['1.3.1'], 'failed'),
('table_07', 'Encontrei páginas em que há células cabeçalho em tabelas com células de dados', '<p>Em tabelas de dados, o contexto que permite dar significado à informação é transmitido pelas células cabeçalho (que se aplicam às linhas ou às colunas da tabela). Estes cabeçalhos devem estar atribuídos, implicitamente ou explicitamente, a células de dados.</p>', 'true', 'all', 'tableHdr', 10, 'A', 1, ['1.3.1'], 'passed'),
('table_08', 'Encontrei páginas em que há células cabeçalho em tabelas sem células de dados', '<p>Em tabelas de dados, o contexto que permite dar significado à informação é transmitido pelas células cabeçalho (que se aplicam às linhas ou às colunas da tabela). Estes cabeçalhos devem estar atribuídos, implicitamente ou explicitamente, a células de dados.</p>', 'prop', 'tableData', 'tableHdrNot', 3, 'A', 1, ['1.3.1'], 'failed'),
('textC_01', 'Combinações de cor com um rácio de contraste superior a 7:1 para texto normal ou 4.5:1 para texto grande', '<p>De acordo com o critério de sucesso 1.4.6, o rácio 4.5 para 1 corresponde ao contraste otimizado para texto "em tamanho grande" (18 pt ou 14 pt negrito, ou maior). Recordo que para tamanho de letra normal o rácio otimizado é de 7 para 1.</p>', 'true', 'all', 'textContrastH', 10, 'AAA', 1, ['1.4.6'], 'passed'),
('textC_02', 'Combinações de cor com um rácio de contraste inferior a 7:1 para texto normal ou 4.5:1 para texto grande', '<p>De acordo com o critério de sucesso 1.4.6, o rácio 4.5 para 1 corresponde ao contraste otimizado para texto "em tamanho grande" (18 pt ou 14 pt negrito, ou maior). Recordo que para tamanho de letra normal o rácio otimizado é de 7 para 1.</p>', 'fals', 'all', 'textContrastHNot', 10, 'AAA', 1, ['1.4.6'], 'warning'),
('title_01', 'Encontrei páginas em que há múltíplos elementos <title>', '<p>Tome nota que o elemento <code>&lt;title&gt;</code> apenas deve aparecer uma vez na página.</p>', 'true', 'all', 'titleVrs', 7, 'A', 1, ['2.4.2'], 'failed'),
('title_02', 'Encontrei páginas em que não há o elemento <title>', '<p>Tome nota que o elemento <code>&lt;title&gt;</code> apenas deve aparecer uma vez na página.</p>', 'true', 'all', 'titleNo', 1, 'A', 1, ['2.4.2'], 'failed'),
('title_03', 'Encontrei páginas em que o elemento <title> está vazio', '<p>Define-se como condição de falha sempre que uma página Web tem um título igual a um título de outra página do mesmo sítio Web. Cada página deve possuir um título único que identifique o propósito dos conteúdos.</p>', 'true', 'all', 'titleNull', 1, 'A', 1, ['2.4.2'], 'failed'),
('title_04', 'Encontrei páginas em que o título da página é demasiado grande', '<p>O <code>&lt;title&gt;</code> de cada página deve: (1) identificar o assunto da página; (2) fazer sentido quando lido fora do contexto; (3) ser curto.</p>', 'decr', 'all', 'titleLong', 10, 'A', 1, ['2.4.2'], 'warning'),
('title_05', 'Encontrei páginas em que o título da página aparenta ser arte-ASCII', '<p>O <code>&lt;title&gt;</code> de cada página deve: (1) identificar o assunto da página; (2) fazer sentido quando lido fora do contexto; (3) ser curto.</p>', 'true', 'all', 'titleChars', 1, 'A', 0.5, ['2.4.2'], 'failed'),
('title_06', 'Encontrei páginas com o <title> correto', '<p>Tome nota que o elemento <code>&lt;title&gt;</code> apenas deve aparecer uma vez na página.</p>', 'true', 'all', 'titleOk', 10, 'A', 0.5, ['2.4.2'], 'passed'),
('values_01a', 'Encontrei páginas com unidades de medida absoluta no HTML', '<p>Amplie 200% o ecrã e verifique que todo o conteúdo é visível sem necessidade de efetuar varrimentos horizontais.</p>', 'decr', 'all', 'valueAbsHtml', 3, 'AA', 0.9, ['1.4.4'], 'warning'),
('values_01b', 'Encontrei páginas com unidades de medida relativa no HTML', '<p>Amplie 200% o ecrã e verifique que todo o conteúdo é visível sem necessidade de efetuar varrimentos horizontais.</p>', 'true', 'all', 'valueRelHtml', 10, 'AA', 0.9, ['1.4.4'], 'passed'),
('values_02a', 'Encontrei páginas com unidades de medida absoluta na CSS', '<p>Amplie 200% o ecrã e verifique que todo o conteúdo é visível sem necessidade de efetuar varrimentos horizontais.</p>', 'decr', 'all', 'valueAbsCss', 5, 'AAA', 0.9, ['1.4.8'], 'warning'),
('values_02b', 'Encontrei páginas com unidades de medida relativa na CSS', '<p>Amplie 200% o ecrã e verifique que todo o conteúdo é visível sem necessidade de efetuar varrimentos horizontais.</p>', 'true', 'all', 'valueRelCss', 10, 'AAA', 1, ['1.4.8'], 'passed'),
('video_01', 'Encontrei páginas com video com conteúdo áudio', '<p>O áudio de um vídeo deve ser apresentado na página sob a forma de uma alternativa acessível. Esta alternativa pode ser a legendagem do vídeo ou a inclusão de texto na página correspondente ao conteúdo áudio do vídeo.</p>', 'true', 'all', 'videoAudit', 10, 'A', 1, ['1.2.2'], 'warning'),
('video_02', 'Encontrei páginas com video com conteúdo visual', '<p>O conteúdo visual de um vídeo deve ser apresentado na página sob a forma de uma alternativa acessível. Esta alternativa pode ser uma áudio descrição ou uma transcrição do vídeo.</p>', 'true', 'all', 'videoVisual', 10, 'A', 1, ['1.2.3'], 'warning'),
('win_01', 'Encontrei páginas onde existem janelas pop-up', '<p>Alguns sítios Web abrem uma nova janela assim que a página carrega, para publicitar um produto ou serviço. Assegure-se que isto não desorienta os utilizadores.</p>', 'true', 'all', 'newWinOnLoad', 3, 'AAA', 0.9, ['3.2.5'], 'warning'),
('word_01', 'Propriedade de CSS word-spacing não impede aumentar espaçamento', '<p>Um espaçamento entre palavras igual ou superior a 0,16 vezes o tamanho da fonte é importante para garantir que todos os utilizadores conseguem ler o texto. Os estilos CSS não devem impedir que os utilizadores aumentem o espaçamento entre palavras se assim o entenderem.</p>', 'true', 'all', 'wordSpacing', 10, 'AA', 1, ['1.4.12'], 'passed'),
('word_02', 'Propriedade de CSS word-spacing impede aumentar espaçamento', '<p>Um espaçamento entre palavras igual ou superior a 0,16 vezes o tamanho da fonte é importante para garantir que todos os utilizadores conseguem ler o texto. Os estilos CSS não devem impedir que os utilizadores aumentem o espaçamento entre palavras se assim o entenderem.</p>', 'fals', 'all', 'wordSpacingNot', 4, 'AA', 1, ['1.4.12'], 'failed');




DROP DICTIONARY IF EXISTS institution_websites_dict;

CREATE DICTIONARY IF NOT EXISTS institution_websites_dict (
    directories_ids Array(Int32),
    website_id UInt64,
    page_count UInt64,
    institution_id Nullable(UInt64),
    institution_name Nullable(String),
    website_title String,
    base_url String,
    stamp Nullable(String),
    declaration_status Nullable(String),
    show_in_observatory Boolean
)
PRIMARY KEY website_id
SOURCE(POSTGRESQL(HOST '172.17.0.1' PORT 5432 USER 'accessmonitor' PASSWORD 'v2password' DB 'Accessibility' TABLE 'v_websites_metadata'))
LIFETIME(MIN 5 MAX 20)
LAYOUT(HASHED());


DROP DICTIONARY IF EXISTS websites_context_dict;

CREATE DICTIONARY IF NOT EXISTS websites_context_dict (
    context_id UInt8,
    website_id UInt32
)
PRIMARY KEY website_id
SOURCE(POSTGRESQL(HOST '172.17.0.1' PORT 5432 USER 'accessmonitor' PASSWORD 'v2password' DB 'Accessibility' TABLE 'context_websites_observatory'))
LIFETIME(MIN 20 MAX 60)
LAYOUT(HASHED());



DROP DICTIONARY IF EXISTS pages_context_dict;

CREATE DICTIONARY IF NOT EXISTS pages_context_dict (
    page_id UInt32
)
PRIMARY KEY page_id
SOURCE(POSTGRESQL(HOST '172.17.0.1' PORT 5432 USER 'accessmonitor' PASSWORD 'v2password' DB 'Accessibility' TABLE 'page_contexts_observatory'))
LIFETIME(MIN 20 MAX 60)
LAYOUT(HASHED());


DROP DICTIONARY IF EXISTS directories_metadata_dict;

CREATE DICTIONARY IF NOT EXISTS directories_metadata_dict (
    id UInt16,
    name String,
    website_ids Array(UInt32),
    show_in_observatory Boolean,
    website_count UInt32,
    total_stamps UInt32,
    total_gold_stamps UInt32,
    total_silver_stamps UInt32,
    total_bronze_stamps UInt32,
    total_declarations UInt32,
    total_conform_declarations UInt32,
    total_nonconform_declarations UInt32,
    total_partiallyconform_declarations UInt32
)
PRIMARY KEY id
SOURCE(POSTGRESQL(HOST '172.17.0.1' PORT 5432 USER 'accessmonitor' PASSWORD 'v2password' DB 'Accessibility' TABLE 'v_directory_websites'))
LIFETIME(MIN 0 MAX 60)
LAYOUT(HASHED());



DROP DICTIONARY IF EXISTS stamps_dict;

CREATE DICTIONARY IF NOT EXISTS stamps_dict (
    website_id UInt32,
    stamp String
)
PRIMARY KEY website_id
SOURCE(POSTGRESQL(HOST '172.17.0.1' PORT 5432 USER 'accessmonitor' PASSWORD 'v2password' DB 'Accessibility' TABLE 'website_stamps'))
LIFETIME(MIN 0 MAX 60)
LAYOUT(HASHED());



DROP DICTIONARY IF EXISTS declarations_dict;

CREATE DICTIONARY IF NOT EXISTS declarations_dict (
    website_id UInt32,
    status String
)
PRIMARY KEY website_id
SOURCE(POSTGRESQL(HOST '172.17.0.1' PORT 5432 USER 'accessmonitor' PASSWORD 'v2password' DB 'Accessibility' TABLE 'website_declarations'))
LIFETIME(MIN 0 MAX 60)
LAYOUT(HASHED());



