name: Nestjs Unit Tests

on:
  push:
    branches: [main, develop, monitor-server-v2]
  pull_request:
    branches: [main, develop, monitor-server-v2]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install Dependencies
        run: npm install
      - name: Run Unit Tests
        run: npm test
